/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var xn = Object.defineProperty;
var Ks = Object.getOwnPropertyDescriptor;
var Xs = Object.getOwnPropertyNames;
var Zs = Object.prototype.hasOwnProperty;
var vi = (e) => {
	throw TypeError(e);
};
var Js = (e, t, r) => (t in e ? xn(e, t, { enumerable: !0, configurable: !0, writable: !0, value: r }) : (e[t] = r));
var Qs = (e, t) => {
		for (var r in t) xn(e, r, { get: t[r], enumerable: !0 });
	},
	ea = (e, t, r, n) => {
		if ((t && typeof t == "object") || typeof t == "function")
			for (let o of Xs(t))
				!Zs.call(e, o) && o !== r && xn(e, o, { get: () => t[o], enumerable: !(n = Ks(t, o)) || n.enumerable });
		return e;
	};
var ta = (e) => ea(xn({}, "__esModule", { value: !0 }), e);
var M = (e, t, r) => Js(e, typeof t != "symbol" ? t + "" : t, r),
	vo = (e, t, r) => t.has(e) || vi("Cannot " + r);
var l = (e, t, r) => (vo(e, t, "read from private field"), r ? r.call(e) : t.get(e)),
	w = (e, t, r) =>
		t.has(e)
			? vi("Cannot add the same private member more than once")
			: t instanceof WeakSet
				? t.add(e)
				: t.set(e, r),
	y = (e, t, r, n) => (vo(e, t, "write to private field"), n ? n.call(e, r) : t.set(e, r), r),
	H = (e, t, r) => (vo(e, t, "access private method"), r);
var Af = {};
Qs(Af, { default: () => co });
module.exports = ta(Af);
var zs = require("obsidian");
var bn = class {
	constructor(t = !0) {
		this.audioContext = null;
		this.enabled = !0;
		this.activeOscillators = [];
		this.loopInterval = null;
		this.enabled = t;
	}
	setEnabled(t) {
		this.enabled = t;
	}
	getContext() {
		return (
			this.audioContext || (this.audioContext = new (window.AudioContext || window.webkitAudioContext)()),
			this.audioContext
		);
	}
	playTone(t, r, n, o = 0) {
		if (!this.enabled) return;
		let i = this.getContext(),
			s = i.createOscillator(),
			a = i.createGain();
		((s.type = r),
			s.frequency.setValueAtTime(t, i.currentTime + o),
			a.gain.setValueAtTime(0.1, i.currentTime + o),
			a.gain.exponentialRampToValueAtTime(1e-5, i.currentTime + o + n),
			s.connect(a),
			a.connect(i.destination),
			s.start(i.currentTime + o),
			s.stop(i.currentTime + o + n),
			this.activeOscillators.push(s),
			(s.onended = () => {
				this.activeOscillators = this.activeOscillators.filter((f) => f !== s);
			}));
	}
	playStart() {
		(this.stopAlarm(), this.playTone(880, "sine", 0.5));
	}
	playPause() {
		(this.stopAlarm(), this.playTone(440, "sine", 0.1), this.playTone(330, "sine", 0.3, 0.1));
	}
	playResume() {
		(this.stopAlarm(), this.playTone(330, "sine", 0.1), this.playTone(440, "sine", 0.3, 0.1));
	}
	playComplete(t = !1) {
		this.stopAlarm();
		let r = () => {
			(this.playTone(523.25, "sine", 0.2, 0),
				this.playTone(659.25, "sine", 0.2, 0 + 0.2),
				this.playTone(783.99, "sine", 0.2, 0 + 0.4),
				this.playTone(1046.5, "sine", 0.6, 0 + 0.6));
		};
		(r(), t && (this.loopInterval = window.setInterval(r, 2e3)));
	}
	stopAlarm() {
		(this.loopInterval && (window.clearInterval(this.loopInterval), (this.loopInterval = null)),
			this.activeOscillators.forEach((t) => {
				try {
					t.stop();
				} catch (r) {}
			}),
			(this.activeOscillators = []));
	}
};
var wr = (e) => {
	let t = Math.floor(e / 60),
		r = e % 60;
	return `${t}:${r.toString().padStart(2, "0")}`;
};
var nr = (e, t, r, n) => {
	if (r === "completed") return 0;
	let o = e * 60,
		i = t;
	if (r === "running") {
		let s = Date.now(),
			a = Math.floor((s - n) / 1e3);
		i += a;
	}
	return Math.max(0, o - i);
};
var yn = class {
	constructor(t, r) {
		this.activeSession = null;
		this.listeners = [];
		this.completionListeners = [];
		((this.settings = t),
			(this.audioService = r),
			this.audioService.setEnabled(t.enableSound !== !1),
			(this.customDuration = t.focusDuration));
	}
	setCustomDuration(t) {
		((this.customDuration = Math.max(1, t)), this.notifyListeners());
	}
	getCustomDuration() {
		return this.customDuration;
	}
	startSession(t, r) {
		let n = Date.now(),
			o = r;
		(o ||
			(t === "Short Break"
				? (o = this.settings.shortBreakDuration)
				: t === "Long Break"
					? (o = this.settings.longBreakDuration)
					: (o = this.customDuration)),
			(this.activeSession = {
				name: t,
				durationMinutes: o,
				startTime: n,
				status: "running",
				elapsed: 0,
				lastResumed: n,
			}),
			this.audioService.playStart(),
			this.notifyListeners());
	}
	pauseSession() {
		if (this.activeSession && this.activeSession.status === "running") {
			let t = Date.now(),
				r = Math.floor((t - this.activeSession.lastResumed) / 1e3);
			((this.activeSession.elapsed += r),
				(this.activeSession.status = "paused"),
				this.audioService.playPause(),
				this.notifyListeners());
		}
	}
	resumeSession() {
		this.activeSession &&
			this.activeSession.status === "paused" &&
			((this.activeSession.status = "running"),
			(this.activeSession.lastResumed = Date.now()),
			this.audioService.playResume(),
			this.notifyListeners());
	}
	stopSession() {
		(this.audioService.stopAlarm(), (this.activeSession = null), this.notifyListeners());
	}
	resetSession() {
		if (this.activeSession) {
			this.audioService.stopAlarm();
			let t = Date.now();
			((this.activeSession.elapsed = 0),
				(this.activeSession.lastResumed = t),
				(this.activeSession.startTime = t),
				(this.activeSession.status = "running"),
				this.notifyListeners());
		}
	}
	addTime(t) {
		this.activeSession &&
			((this.activeSession.durationMinutes += t),
			this.activeSession.status === "completed" &&
				(this.audioService.stopAlarm(),
				(this.activeSession.status = "running"),
				(this.activeSession.lastResumed = Date.now())),
			this.notifyListeners());
	}
	tick() {
		this.activeSession &&
			this.activeSession.status === "running" &&
			nr(
				this.activeSession.durationMinutes,
				this.activeSession.elapsed,
				this.activeSession.status,
				this.activeSession.lastResumed,
			) <= 0 &&
			this.completeSession();
	}
	completeSession() {
		this.activeSession &&
			((this.activeSession.status = "completed"),
			this.audioService.playComplete(!0),
			this.notifyListeners(),
			this.notifyCompletion(this.activeSession));
	}
	getActiveSession() {
		return this.activeSession;
	}
	onChange(t) {
		this.listeners.push(t);
	}
	onSessionComplete(t) {
		this.completionListeners.push(t);
	}
	removeListener(t) {
		this.listeners = this.listeners.filter((r) => r !== t);
	}
	notifyListeners() {
		this.listeners.forEach((t) => t());
	}
	notifyCompletion(t) {
		this.completionListeners.forEach((r) => r(t));
	}
};
var Vs = require("obsidian");
var gi,
	xi,
	hi = (xi = (gi = globalThis.process) == null ? void 0 : gi.env) == null ? void 0 : xi.NODE_ENV,
	p = hi && !hi.toLowerCase().startsWith("prod");
var At = Array.isArray,
	bi = Array.prototype.indexOf,
	ho = Array.from,
	go = Object.keys,
	X = Object.defineProperty,
	Ce = Object.getOwnPropertyDescriptor,
	xo = Object.getOwnPropertyDescriptors,
	bo = Object.prototype,
	yi = Array.prototype,
	Er = Object.getPrototypeOf,
	yo = Object.isExtensible;
var ne = () => {};
function wi(e) {
	return e();
}
function or(e) {
	for (var t = 0; t < e.length; t++) e[t]();
}
function wn() {
	var e,
		t,
		r = new Promise((n, o) => {
			((e = n), (t = o));
		});
	return { promise: r, resolve: e, reject: t };
}
var oe = Symbol("$state"),
	En = Symbol("legacy props"),
	na = Symbol(""),
	$n = Symbol("proxy path"),
	pt = new (class extends Error {
		constructor() {
			super(...arguments);
			M(this, "name", "StaleReactionError");
			M(this, "message", "The reaction that called `getAbortSignal()` was re-run or destroyed");
		}
	})();
var Kr = 3,
	Re = 8;
function Sn(e) {
	if (p) {
		let t = new Error(`lifecycle_outside_component
\`${e}(...)\` can only be used during component initialisation
https://svelte.dev/e/lifecycle_outside_component`);
		throw ((t.name = "Svelte error"), t);
	} else throw new Error("https://svelte.dev/e/lifecycle_outside_component");
}
function Ei() {
	if (p) {
		let e = new Error(
			"async_derived_orphan\nCannot create a `$derived(...)` with an `await` expression outside of an effect tree\nhttps://svelte.dev/e/async_derived_orphan",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/async_derived_orphan");
}
function $i() {
	if (p) {
		let e = new Error(`derived_references_self
A derived value cannot reference itself recursively
https://svelte.dev/e/derived_references_self`);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/derived_references_self");
}
function Si(e) {
	if (p) {
		let t = new Error(`effect_in_teardown
\`${e}\` cannot be used inside an effect cleanup function
https://svelte.dev/e/effect_in_teardown`);
		throw ((t.name = "Svelte error"), t);
	} else throw new Error("https://svelte.dev/e/effect_in_teardown");
}
function Ti() {
	if (p) {
		let e = new Error(
			"effect_in_unowned_derived\nEffect cannot be created inside a `$derived` value that was not itself created inside an effect\nhttps://svelte.dev/e/effect_in_unowned_derived",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/effect_in_unowned_derived");
}
function Ai(e) {
	if (p) {
		let t = new Error(`effect_orphan
\`${e}\` can only be used inside an effect (e.g. during component initialisation)
https://svelte.dev/e/effect_orphan`);
		throw ((t.name = "Svelte error"), t);
	} else throw new Error("https://svelte.dev/e/effect_orphan");
}
function ki() {
	if (p) {
		let e = new Error(`effect_update_depth_exceeded
Maximum update depth exceeded. This typically indicates that an effect reads and writes the same piece of state
https://svelte.dev/e/effect_update_depth_exceeded`);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/effect_update_depth_exceeded");
}
function Ni() {
	if (p) {
		let e = new Error(`hydration_failed
Failed to hydrate the application
https://svelte.dev/e/hydration_failed`);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/hydration_failed");
}
function Ci(e) {
	if (p) {
		let t = new Error(`rune_outside_svelte
The \`${e}\` rune is only available inside \`.svelte\` and \`.svelte.js/ts\` files
https://svelte.dev/e/rune_outside_svelte`);
		throw ((t.name = "Svelte error"), t);
	} else throw new Error("https://svelte.dev/e/rune_outside_svelte");
}
function Ri() {
	if (p) {
		let e = new Error(
			"state_descriptors_fixed\nProperty descriptors defined on `$state` objects must contain `value` and always be `enumerable`, `configurable` and `writable`.\nhttps://svelte.dev/e/state_descriptors_fixed",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/state_descriptors_fixed");
}
function Di() {
	if (p) {
		let e = new Error(
			"state_prototype_fixed\nCannot set prototype of `$state` object\nhttps://svelte.dev/e/state_prototype_fixed",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/state_prototype_fixed");
}
function Mi() {
	if (p) {
		let e = new Error(
			"state_unsafe_mutation\nUpdating state inside `$derived(...)`, `$inspect(...)` or a template expression is forbidden. If the value should not be reactive, declare it without `$state`\nhttps://svelte.dev/e/state_unsafe_mutation",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/state_unsafe_mutation");
}
function Oi() {
	if (p) {
		let e = new Error(
			"svelte_boundary_reset_onerror\nA `<svelte:boundary>` `reset` function cannot be called while an error is still being handled\nhttps://svelte.dev/e/svelte_boundary_reset_onerror",
		);
		throw ((e.name = "Svelte error"), e);
	} else throw new Error("https://svelte.dev/e/svelte_boundary_reset_onerror");
}
var Xr = "[",
	kt = "[!",
	$r = "]",
	Nt = {};
var I = Symbol(),
	Ue = Symbol("filename"),
	Ii = Symbol("hmr");
var Sr = "font-weight: bold",
	Tr = "font-weight: normal";
function Li(e, t) {
	p
		? console.warn(
				`%c[svelte] await_waterfall
%cAn async derived, \`${e}\` (${t}) was not read immediately after it resolved. This often indicates an unnecessary waterfall, which can slow down your app
https://svelte.dev/e/await_waterfall`,
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/await_waterfall");
}
function ir(e) {
	p
		? console.warn(
				`%c[svelte] hydration_mismatch
%c${e ? `Hydration failed because the initial UI does not match what was rendered on the server. The error occurred near ${e}` : "Hydration failed because the initial UI does not match what was rendered on the server"}
https://svelte.dev/e/hydration_mismatch`,
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/hydration_mismatch");
}
function Fi() {
	p
		? console.warn(
				`%c[svelte] lifecycle_double_unmount
%cTried to unmount a component that was not mounted
https://svelte.dev/e/lifecycle_double_unmount`,
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/lifecycle_double_unmount");
}
function Tn(e) {
	p
		? console.warn(
				`%c[svelte] state_proxy_equality_mismatch
%cReactive \`$state(...)\` proxies and the values they proxy have different identities. Because of this, comparisons with \`${e}\` will produce unexpected results
https://svelte.dev/e/state_proxy_equality_mismatch`,
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/state_proxy_equality_mismatch");
}
function Pi() {
	p
		? console.warn(
				`%c[svelte] state_proxy_unmount
%cTried to unmount a state proxy, rather than a component
https://svelte.dev/e/state_proxy_unmount`,
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/state_proxy_unmount");
}
function Bi() {
	p
		? console.warn(
				"%c[svelte] svelte_boundary_reset_noop\n%cA `<svelte:boundary>` `reset` function only resets the boundary the first time it is called\nhttps://svelte.dev/e/svelte_boundary_reset_noop",
				Sr,
				Tr,
			)
		: console.warn("https://svelte.dev/e/svelte_boundary_reset_noop");
}
var b = !1;
function fe(e) {
	b = e;
}
var E;
function B(e) {
	if (e === null) throw (ir(), Nt);
	return (E = e);
}
function le() {
	return B(se(E));
}
function S(e) {
	if (b) {
		if (se(E) !== null) throw (ir(), Nt);
		E = e;
	}
}
function sr(e = 1) {
	if (b) {
		for (var t = e, r = E; t--; ) r = se(r);
		E = r;
	}
}
function ar(e = !0) {
	for (var t = 0, r = E; ; ) {
		if (r.nodeType === Re) {
			var n = r.data;
			if (n === $r) {
				if (t === 0) return r;
				t -= 1;
			} else (n === Xr || n === kt) && (t += 1);
		}
		var o = se(r);
		(e && r.remove(), (r = o));
	}
}
function wo(e) {
	if (!e || e.nodeType !== Re) throw (ir(), Nt);
	return e.data;
}
function An(e) {
	return e === this.v;
}
function Zr(e, t) {
	return e != e ? t == t : e !== t || (e !== null && typeof e == "object") || typeof e == "function";
}
function kn(e) {
	return !Zr(e, this.v);
}
var we = !1,
	Ct = !1,
	rt = !1;
function qi() {
	Ct = !0;
}
var Jr = null;
function Ee(e, t) {
	return ((e.label = t), Nn(e.v, t), e);
}
function Nn(e, t) {
	var r;
	return ((r = e == null ? void 0 : e[$n]) == null || r.call(e, t), e);
}
function dt(e) {
	let t = new Error(),
		r = ia();
	return r.length === 0
		? null
		: (r.unshift(`
`),
			X(t, "stack", {
				value: r.join(`
`),
			}),
			X(t, "name", { value: e }),
			t);
}
function ia() {
	let e = Error.stackTraceLimit;
	Error.stackTraceLimit = 1 / 0;
	let t = new Error().stack;
	if (((Error.stackTraceLimit = e), !t)) return [];
	let r = t.split(`
`),
		n = [];
	for (let o = 0; o < r.length; o++) {
		let i = r[o],
			s = i.replaceAll("\\", "/");
		if (i.trim() !== "Error") {
			if (i.includes("validate_each_keys")) return [];
			s.includes("svelte/src/internal") || s.includes("node_modules/.vite") || n.push(i);
		}
	}
	return n;
}
var $ = null;
function Dt(e) {
	$ = e;
}
var _t = null;
function Ar(e) {
	_t = e;
}
var nt = null;
function Cn(e) {
	nt = e;
}
function ce(e, t = !1, r) {
	(($ = { p: $, i: !1, c: null, e: null, s: e, x: null, l: Ct && !t ? { s: null, u: null, $: [] } : null }),
		p && (($.function = r), (nt = r)));
}
function ue(e) {
	var o;
	var t = $,
		r = t.e;
	if (r !== null) {
		t.e = null;
		for (var n of r) $o(n);
	}
	return (
		e !== void 0 && (t.x = e),
		(t.i = !0),
		($ = t.p),
		p && (nt = (o = $ == null ? void 0 : $.function) != null ? o : null),
		e != null ? e : {}
	);
}
function mt() {
	return !Ct || ($ !== null && $.l === null);
}
var fr = [];
function Yi() {
	var e = fr;
	((fr = []), or(e));
}
function pe(e) {
	if (fr.length === 0 && !lr) {
		var t = fr;
		queueMicrotask(() => {
			t === fr && Yi();
		});
	}
	fr.push(e);
}
function Ui() {
	for (; fr.length > 0; ) Yi();
}
var So = new WeakMap();
function Rn(e) {
	var t = h;
	if (t === null) return ((x.f |= 8388608), e);
	if ((p && e instanceof Error && !So.has(e) && So.set(e, sa(e, t)), (t.f & 32768) === 0)) {
		if ((t.f & 128) === 0) throw (p && !t.parent && e instanceof Error && Hi(e), e);
		t.b.error(e);
	} else vt(e, t);
}
function vt(e, t) {
	for (; t !== null; ) {
		if ((t.f & 128) !== 0)
			try {
				t.b.error(e);
				return;
			} catch (r) {
				e = r;
			}
		t = t.parent;
	}
	throw (p && e instanceof Error && Hi(e), e);
}
function sa(e, t) {
	var s, a, f;
	let r = Ce(e, "message");
	if (!(r && !r.configurable)) {
		for (
			var n = Qr ? "  " : "	",
				o = `
${n}in ${((s = t.fn) == null ? void 0 : s.name) || "<unknown>"}`,
				i = t.ctx;
			i !== null;
		)
			((o += `
${n}in ${(a = i.function) == null ? void 0 : a[Ue].split("/").pop()}`),
				(i = i.p));
		return {
			message:
				e.message +
				`
${o}
`,
			stack:
				(f = e.stack) == null
					? void 0
					: f
							.split(
								`
`,
							)
							.filter((c) => !c.includes("svelte/src/internal")).join(`
`),
		};
	}
}
function Hi(e) {
	let t = So.get(e);
	t && (X(e, "message", { value: t.message }), X(e, "stack", { value: t.stack }));
}
var aa = -7169;
function O(e, t) {
	e.f = (e.f & aa) | t;
}
function Nr(e) {
	(e.f & 512) !== 0 || e.deps === null ? O(e, 1024) : O(e, 4096);
}
function Gi(e) {
	if (e !== null) for (let t of e) (t.f & 2) === 0 || (t.f & 32768) === 0 || ((t.f ^= 32768), Gi(t.deps));
}
function Dn(e, t, r) {
	((e.f & 2048) !== 0 ? t.add(e) : (e.f & 4096) !== 0 && r.add(e), Gi(e.deps), O(e, 1024));
}
var Cr = new Set(),
	k = null,
	en = null,
	z = null,
	He = [],
	In = null,
	To = !1,
	lr = !1,
	Rr,
	Dr,
	cr,
	ur,
	nn,
	Mr,
	Or,
	je,
	Ao,
	ko,
	zi,
	Wi,
	Mn = class Mn {
		constructor() {
			w(this, je);
			M(this, "committed", !1);
			M(this, "current", new Map());
			M(this, "previous", new Map());
			w(this, Rr, new Set());
			w(this, Dr, new Set());
			w(this, cr, 0);
			w(this, ur, 0);
			w(this, nn, null);
			w(this, Mr, new Set());
			w(this, Or, new Set());
			M(this, "skipped_effects", new Set());
			M(this, "is_fork", !1);
		}
		is_deferred() {
			return this.is_fork || l(this, ur) > 0;
		}
		process(t) {
			var o;
			((He = []), (en = null), this.apply());
			var r = [],
				n = [];
			for (let i of t) H(this, je, Ao).call(this, i, r, n);
			(this.is_fork || H(this, je, zi).call(this),
				this.is_deferred()
					? (H(this, je, ko).call(this, n), H(this, je, ko).call(this, r))
					: ((en = this), (k = null), ji(n), ji(r), (en = null), (o = l(this, nn)) == null || o.resolve()),
				(z = null));
		}
		capture(t, r) {
			(r !== I && !this.previous.has(t) && this.previous.set(t, r),
				(t.f & 8388608) === 0 && (this.current.set(t, t.v), z == null || z.set(t, t.v)));
		}
		activate() {
			((k = this), this.apply());
		}
		deactivate() {
			k === this && ((k = null), (z = null));
		}
		flush() {
			if ((this.activate(), He.length > 0)) {
				if ((No(), k !== null && k !== this)) return;
			} else l(this, cr) === 0 && this.process([]);
			this.deactivate();
		}
		discard() {
			for (let t of l(this, Dr)) t(this);
			l(this, Dr).clear();
		}
		increment(t) {
			(y(this, cr, l(this, cr) + 1), t && y(this, ur, l(this, ur) + 1));
		}
		decrement(t) {
			(y(this, cr, l(this, cr) - 1), t && y(this, ur, l(this, ur) - 1), this.revive());
		}
		revive() {
			for (let t of l(this, Mr)) (l(this, Or).delete(t), O(t, 2048), Oe(t));
			for (let t of l(this, Or)) (O(t, 4096), Oe(t));
			this.flush();
		}
		oncommit(t) {
			l(this, Rr).add(t);
		}
		ondiscard(t) {
			l(this, Dr).add(t);
		}
		settled() {
			var t;
			return ((t = l(this, nn)) != null ? t : y(this, nn, wn())).promise;
		}
		static ensure() {
			if (k === null) {
				let t = (k = new Mn());
				(Cr.add(k),
					lr ||
						Mn.enqueue(() => {
							k === t && t.flush();
						}));
			}
			return k;
		}
		static enqueue(t) {
			pe(t);
		}
		apply() {
			if (!(!we || (!this.is_fork && Cr.size === 1))) {
				z = new Map(this.current);
				for (let t of Cr) if (t !== this) for (let [r, n] of t.previous) z.has(r) || z.set(r, n);
			}
		}
	};
((Rr = new WeakMap()),
	(Dr = new WeakMap()),
	(cr = new WeakMap()),
	(ur = new WeakMap()),
	(nn = new WeakMap()),
	(Mr = new WeakMap()),
	(Or = new WeakMap()),
	(je = new WeakSet()),
	(Ao = function (t, r, n) {
		var u;
		t.f ^= 1024;
		for (var o = t.first, i = null; o !== null; ) {
			var s = o.f,
				a = (s & 96) !== 0,
				f = a && (s & 1024) !== 0,
				c = f || (s & 8192) !== 0 || this.skipped_effects.has(o);
			if (
				(we && i === null && (s & 128) !== 0 && (u = o.b) != null && u.is_pending && (i = o),
				!c && o.fn !== null)
			) {
				a
					? (o.f ^= 1024)
					: i !== null && (s & 16777228) !== 0
						? i.b.defer_effect(o)
						: (s & 4) !== 0
							? r.push(o)
							: we && (s & 16777224) !== 0
								? n.push(o)
								: Zt(o) && ((s & 16) !== 0 && l(this, Mr).add(o), Xt(o));
				var m = o.first;
				if (m !== null) {
					o = m;
					continue;
				}
			}
			var _ = o.parent;
			for (o = o.next; o === null && _ !== null; ) (_ === i && (i = null), (o = _.next), (_ = _.parent));
		}
	}),
	(ko = function (t) {
		for (var r = 0; r < t.length; r += 1) Dn(t[r], l(this, Mr), l(this, Or));
	}),
	(zi = function () {
		if (l(this, ur) === 0) {
			for (let t of l(this, Rr)) t();
			l(this, Rr).clear();
		}
		l(this, cr) === 0 && H(this, je, Wi).call(this);
	}),
	(Wi = function () {
		var o;
		if (Cr.size > 1) {
			this.previous.clear();
			var t = z,
				r = !0;
			for (let i of Cr) {
				if (i === this) {
					r = !1;
					continue;
				}
				let s = [];
				for (let [f, c] of this.current) {
					if (i.current.has(f))
						if (r && c !== i.current.get(f)) i.current.set(f, c);
						else continue;
					s.push(f);
				}
				if (s.length === 0) continue;
				let a = [...i.current.keys()].filter((f) => !this.current.has(f));
				if (a.length > 0) {
					var n = He;
					He = [];
					let f = new Set(),
						c = new Map();
					for (let m of s) Ki(m, a, f, c);
					if (He.length > 0) {
						((k = i), i.apply());
						for (let m of He) H((o = i), je, Ao).call(o, m, [], []);
						i.deactivate();
					}
					He = n;
				}
			}
			((k = null), (z = t));
		}
		((this.committed = !0), Cr.delete(this));
	}));
var _e = Mn;
function Fr(e) {
	var t = lr;
	lr = !0;
	try {
		var r;
		for (e && (k !== null && No(), (r = e())); ; ) {
			if ((Ui(), He.length === 0 && (k == null || k.flush(), He.length === 0))) return ((In = null), r);
			No();
		}
	} finally {
		lr = t;
	}
}
function No() {
	var s;
	var e = Ot;
	To = !0;
	var t = p ? new Set() : null;
	try {
		var r = 0;
		for (Ir(!0); He.length > 0; ) {
			var n = _e.ensure();
			if (r++ > 1e3) {
				if (p) {
					var o = new Map();
					for (let a of n.current.keys())
						for (let [f, c] of (s = a.updated) != null ? s : []) {
							var i = o.get(f);
							(i || ((i = { error: c.error, count: 0 }), o.set(f, i)), (i.count += c.count));
						}
					for (let a of o.values()) a.error && console.error(a.error);
				}
				la();
			}
			if ((n.process(He), ht.clear(), p)) for (let a of n.current.keys()) t.add(a);
		}
	} finally {
		if (((To = !1), Ir(e), (In = null), p)) for (let a of t) a.updated = null;
	}
}
function la() {
	try {
		ki();
	} catch (e) {
		(p && X(e, "stack", { value: "" }), vt(e, In));
	}
}
var $e = null;
function ji(e) {
	var t = e.length;
	if (t !== 0) {
		for (var r = 0; r < t; ) {
			var n = e[r++];
			if (
				(n.f & 24576) === 0 &&
				Zt(n) &&
				(($e = new Set()),
				Xt(n),
				n.deps === null &&
					n.first === null &&
					n.nodes === null &&
					(n.teardown === null && n.ac === null ? Co(n) : (n.fn = null)),
				($e == null ? void 0 : $e.size) > 0)
			) {
				ht.clear();
				for (let o of $e) {
					if ((o.f & 24576) !== 0) continue;
					let i = [o],
						s = o.parent;
					for (; s !== null; ) ($e.has(s) && ($e.delete(s), i.push(s)), (s = s.parent));
					for (let a = i.length - 1; a >= 0; a--) {
						let f = i[a];
						(f.f & 24576) === 0 && Xt(f);
					}
				}
				$e.clear();
			}
		}
		$e = null;
	}
}
function Ki(e, t, r, n) {
	if (!r.has(e) && (r.add(e), e.reactions !== null))
		for (let o of e.reactions) {
			let i = o.f;
			(i & 2) !== 0
				? Ki(o, t, r, n)
				: (i & 4194320) !== 0 && (i & 2048) === 0 && Xi(o, t, n) && (O(o, 2048), Oe(o));
		}
}
function Xi(e, t, r) {
	let n = r.get(e);
	if (n !== void 0) return n;
	if (e.deps !== null)
		for (let o of e.deps) {
			if (t.includes(o)) return !0;
			if ((o.f & 2) !== 0 && Xi(o, t, r)) return (r.set(o, !0), !0);
		}
	return (r.set(e, !1), !1);
}
function Oe(e) {
	for (var t = (In = e); t.parent !== null; ) {
		t = t.parent;
		var r = t.f;
		if (To && t === h && (r & 16) !== 0 && (r & 262144) === 0) return;
		if ((r & 96) !== 0) {
			if ((r & 1024) === 0) return;
			t.f ^= 1024;
		}
	}
	He.push(t);
}
function Ro(e) {
	let t = 0,
		r = Se(0),
		n;
	return (
		p && Ee(r, "createSubscriber version"),
		() => {
			Rt() &&
				(N(r),
				ee(
					() => (
						t === 0 && (n = L(() => e(() => dr(r)))),
						(t += 1),
						() => {
							pe(() => {
								((t -= 1), t === 0 && (n == null || n(), (n = void 0), dr(r)));
							});
						}
					),
				));
		}
	);
}
var ua = 589952;
function Io(e, t, r) {
	new Do(e, t, r);
}
var Le,
	on,
	gt,
	_r,
	xt,
	ze,
	Te,
	bt,
	It,
	Jt,
	mr,
	Lt,
	vr,
	Br,
	qr,
	Ft,
	qn,
	j,
	Ji,
	Qi,
	Mo,
	Pn,
	Bn,
	Oo,
	Do = class {
		constructor(t, r, n) {
			w(this, j);
			M(this, "parent");
			M(this, "is_pending", !1);
			w(this, Le);
			w(this, on, b ? E : null);
			w(this, gt);
			w(this, _r);
			w(this, xt);
			w(this, ze, null);
			w(this, Te, null);
			w(this, bt, null);
			w(this, It, null);
			w(this, Jt, null);
			w(this, mr, 0);
			w(this, Lt, 0);
			w(this, vr, !1);
			w(this, Br, new Set());
			w(this, qr, new Set());
			w(this, Ft, null);
			w(
				this,
				qn,
				Ro(
					() => (
						y(this, Ft, Se(l(this, mr))),
						p && Ee(l(this, Ft), "$effect.pending()"),
						() => {
							y(this, Ft, null);
						}
					),
				),
			);
			(y(this, Le, t),
				y(this, gt, r),
				y(this, _r, n),
				(this.parent = h.b),
				(this.is_pending = !!l(this, gt).pending),
				y(
					this,
					xt,
					We(() => {
						if (((h.b = this), b)) {
							let i = l(this, on);
							(le(),
								i.nodeType === Re && i.data === kt
									? H(this, j, Qi).call(this)
									: (H(this, j, Ji).call(this), l(this, Lt) === 0 && (this.is_pending = !1)));
						} else {
							var o = H(this, j, Mo).call(this);
							try {
								y(
									this,
									ze,
									me(() => n(o)),
								);
							} catch (i) {
								this.error(i);
							}
							l(this, Lt) > 0 ? H(this, j, Bn).call(this) : (this.is_pending = !1);
						}
						return () => {
							var i;
							(i = l(this, Jt)) == null || i.remove();
						};
					}, ua),
				),
				b && y(this, Le, E));
		}
		defer_effect(t) {
			Dn(t, l(this, Br), l(this, qr));
		}
		is_rendered() {
			return !this.is_pending && (!this.parent || this.parent.is_rendered());
		}
		has_pending_snippet() {
			return !!l(this, gt).pending;
		}
		update_pending_count(t) {
			(H(this, j, Oo).call(this, t), y(this, mr, l(this, mr) + t), l(this, Ft) && Bt(l(this, Ft), l(this, mr)));
		}
		get_effect_pending() {
			return (l(this, qn).call(this), N(l(this, Ft)));
		}
		error(t) {
			var r = l(this, gt).onerror;
			let n = l(this, gt).failed;
			if (l(this, vr) || (!r && !n)) throw t;
			(l(this, ze) && (G(l(this, ze)), y(this, ze, null)),
				l(this, Te) && (G(l(this, Te)), y(this, Te, null)),
				l(this, bt) && (G(l(this, bt)), y(this, bt, null)),
				b && (B(l(this, on)), sr(), B(ar())));
			var o = !1,
				i = !1;
			let s = () => {
				if (o) {
					Bi();
					return;
				}
				((o = !0),
					i && Oi(),
					_e.ensure(),
					y(this, mr, 0),
					l(this, bt) !== null &&
						Qt(l(this, bt), () => {
							y(this, bt, null);
						}),
					(this.is_pending = this.has_pending_snippet()),
					y(
						this,
						ze,
						H(this, j, Pn).call(
							this,
							() => (y(this, vr, !1), me(() => l(this, _r).call(this, l(this, Le)))),
						),
					),
					l(this, Lt) > 0 ? H(this, j, Bn).call(this) : (this.is_pending = !1));
			};
			var a = x;
			try {
				(U(null), (i = !0), r == null || r(t, s), (i = !1));
			} catch (f) {
				vt(f, l(this, xt) && l(this, xt).parent);
			} finally {
				U(a);
			}
			n &&
				pe(() => {
					y(
						this,
						bt,
						H(this, j, Pn).call(this, () => {
							(_e.ensure(), y(this, vr, !0));
							try {
								return me(() => {
									n(
										l(this, Le),
										() => t,
										() => s,
									);
								});
							} catch (f) {
								return (vt(f, l(this, xt).parent), null);
							} finally {
								y(this, vr, !1);
							}
						}),
					);
				});
		}
	};
((Le = new WeakMap()),
	(on = new WeakMap()),
	(gt = new WeakMap()),
	(_r = new WeakMap()),
	(xt = new WeakMap()),
	(ze = new WeakMap()),
	(Te = new WeakMap()),
	(bt = new WeakMap()),
	(It = new WeakMap()),
	(Jt = new WeakMap()),
	(mr = new WeakMap()),
	(Lt = new WeakMap()),
	(vr = new WeakMap()),
	(Br = new WeakMap()),
	(qr = new WeakMap()),
	(Ft = new WeakMap()),
	(qn = new WeakMap()),
	(j = new WeakSet()),
	(Ji = function () {
		try {
			y(
				this,
				ze,
				me(() => l(this, _r).call(this, l(this, Le))),
			);
		} catch (t) {
			this.error(t);
		}
	}),
	(Qi = function () {
		let t = l(this, gt).pending;
		t &&
			(y(
				this,
				Te,
				me(() => t(l(this, Le))),
			),
			_e.enqueue(() => {
				var r = H(this, j, Mo).call(this);
				(y(
					this,
					ze,
					H(this, j, Pn).call(this, () => (_e.ensure(), me(() => l(this, _r).call(this, r)))),
				),
					l(this, Lt) > 0
						? H(this, j, Bn).call(this)
						: (Qt(l(this, Te), () => {
								y(this, Te, null);
							}),
							(this.is_pending = !1)));
			}));
	}),
	(Mo = function () {
		var t = l(this, Le);
		return (this.is_pending && (y(this, Jt, ae()), l(this, Le).before(l(this, Jt)), (t = l(this, Jt))), t);
	}),
	(Pn = function (t) {
		var r = h,
			n = x,
			o = $;
		(W(l(this, xt)), U(l(this, xt)), Dt(l(this, xt).ctx));
		try {
			return t();
		} catch (i) {
			return (Rn(i), null);
		} finally {
			(W(r), U(n), Dt(o));
		}
	}),
	(Bn = function () {
		let t = l(this, gt).pending;
		(l(this, ze) !== null &&
			(y(this, It, document.createDocumentFragment()),
			l(this, It).append(l(this, Jt)),
			Vn(l(this, ze), l(this, It))),
			l(this, Te) === null &&
				y(
					this,
					Te,
					me(() => t(l(this, Le))),
				));
	}),
	(Oo = function (t) {
		var r;
		if (!this.has_pending_snippet()) {
			this.parent && H((r = this.parent), j, Oo).call(r, t);
			return;
		}
		if ((y(this, Lt, l(this, Lt) + t), l(this, Lt) === 0)) {
			this.is_pending = !1;
			for (let n of l(this, Br)) (O(n, 2048), Oe(n));
			for (let n of l(this, qr)) (O(n, 4096), Oe(n));
			(l(this, Br).clear(),
				l(this, qr).clear(),
				l(this, Te) &&
					Qt(l(this, Te), () => {
						y(this, Te, null);
					}),
				l(this, It) && (l(this, Le).before(l(this, It)), y(this, It, null)));
		}
	}));
function Yn(e, t, r, n) {
	let o = mt() ? Yr : an;
	if (r.length === 0 && e.length === 0) {
		n(t.map(o));
		return;
	}
	var i = k,
		s = h,
		a = es();
	function f() {
		Promise.all(r.map((c) => Fo(c)))
			.then((c) => {
				a();
				try {
					n([...t.map(o), ...c]);
				} catch (m) {
					(s.f & 16384) === 0 && vt(m, s);
				}
				(i == null || i.deactivate(), Vr());
			})
			.catch((c) => {
				vt(c, s);
			});
	}
	e.length > 0
		? Promise.all(e).then(() => {
				a();
				try {
					return f();
				} finally {
					(i == null || i.deactivate(), Vr());
				}
			})
		: f();
}
function es() {
	var e = h,
		t = x,
		r = $,
		n = k;
	if (p) var o = _t;
	return function (s = !0) {
		(W(e), U(t), Dt(r), s && (n == null || n.activate()), p && (Lo(null), Ar(o)));
	};
}
function Vr() {
	(W(null), U(null), Dt(null), p && (Lo(null), Ar(null)));
}
var sn = null;
function Lo(e) {
	sn = e;
}
var fn = new Set();
function Yr(e) {
	var t = 2050,
		r = x !== null && (x.f & 2) !== 0 ? x : null;
	h !== null && (h.f |= 524288);
	let n = {
		ctx: $,
		deps: null,
		effects: null,
		equals: An,
		f: t,
		fn: e,
		reactions: null,
		rv: 0,
		v: I,
		wv: 0,
		parent: r != null ? r : h,
		ac: null,
	};
	return (p && rt && (n.created = dt("created at")), n);
}
function Fo(e, t, r) {
	let n = h;
	n === null && Ei();
	var o = n.b,
		i = void 0,
		s = Se(I);
	p && (s.label = t);
	var a = !x,
		f = new Map();
	return (
		ts(() => {
			var d;
			p && (sn = h);
			var c = wn();
			i = c.promise;
			try {
				Promise.resolve(e())
					.then(c.resolve, c.reject)
					.then(() => {
						(m === k && m.committed && m.deactivate(), Vr());
					});
			} catch (v) {
				(c.reject(v), Vr());
			}
			p && (sn = null);
			var m = k;
			if (a) {
				var _ = o.is_rendered();
				(o.update_pending_count(1),
					m.increment(_),
					(d = f.get(m)) == null || d.reject(pt),
					f.delete(m),
					f.set(m, c));
			}
			let u = (v, g = void 0) => {
				if (((sn = null), m.activate(), g)) g !== pt && ((s.f |= 8388608), Bt(s, g));
				else {
					((s.f & 8388608) !== 0 && (s.f ^= 8388608), Bt(s, v));
					for (let [A, P] of f) {
						if ((f.delete(A), A === m)) break;
						P.reject(pt);
					}
					p &&
						r !== void 0 &&
						(fn.add(s),
						setTimeout(() => {
							fn.has(s) && (Li(s.label, r), fn.delete(s));
						}));
				}
				a && (o.update_pending_count(-1), m.decrement(_));
			};
			c.promise.then(u, (v) => u(null, v || "unknown"));
		}),
		te(() => {
			for (let c of f.values()) c.reject(pt);
		}),
		p && (s.f |= 4194304),
		new Promise((c) => {
			function m(_) {
				function u() {
					_ === i ? c(s) : m(i);
				}
				_.then(u, u);
			}
			m(i);
		})
	);
}
function an(e) {
	let t = Yr(e);
	return ((t.equals = kn), t);
}
function Un(e) {
	var t = e.effects;
	if (t !== null) {
		e.effects = null;
		for (var r = 0; r < t.length; r += 1) G(t[r]);
	}
}
var Po = [];
function _a(e) {
	for (var t = e.parent; t !== null; ) {
		if ((t.f & 2) === 0) return (t.f & 16384) === 0 ? t : null;
		t = t.parent;
	}
	return null;
}
function ln(e) {
	var t,
		r = h;
	if ((W(_a(e)), p)) {
		let n = hr;
		Ln(new Set());
		try {
			(Po.includes(e) && $i(), Po.push(e), (e.f &= -32769), Un(e), (t = Hn(e)));
		} finally {
			(W(r), Ln(n), Po.pop());
		}
	} else
		try {
			((e.f &= -32769), Un(e), (t = Hn(e)));
		} finally {
			W(r);
		}
	return t;
}
function Bo(e) {
	var r, n;
	var t = ln(e);
	if (
		!e.equals(t) &&
		((e.wv = Pr()), (!((r = k) != null && r.is_fork) || e.deps === null) && ((e.v = t), e.deps === null))
	) {
		O(e, 1024);
		return;
	}
	at || (z !== null ? (Rt() || ((n = k) != null && n.is_fork)) && z.set(e, t) : Nr(e));
}
var hr = new Set(),
	ht = new Map();
function Ln(e) {
	hr = e;
}
var Vo = !1;
function rs() {
	Vo = !0;
}
function Se(e, t) {
	var r = { f: 0, v: e, reactions: null, equals: An, rv: 0, wv: 0 };
	return (
		p &&
			rt &&
			((r.created = t != null ? t : dt("created at")),
			(r.updated = null),
			(r.set_during_effect = !1),
			(r.trace = null)),
		r
	);
}
function Ke(e, t) {
	let r = Se(e, t);
	return (qo(r), r);
}
function gr(e, t = !1, r = !0) {
	var o, i;
	let n = Se(e);
	return (
		t || (n.equals = kn),
		Ct && r && $ !== null && $.l !== null && ((i = (o = $.l).s) != null ? i : (o.s = [])).push(n),
		n
	);
}
function Z(e, t, r = !1) {
	var o;
	x !== null &&
		(!Ae || (x.f & 131072) !== 0) &&
		mt() &&
		(x.f & 4325394) !== 0 &&
		!((o = ke) != null && o.includes(e)) &&
		Mi();
	let n = r ? er(t) : t;
	return (p && Nn(n, e.label), Bt(e, n));
}
function Bt(e, t) {
	var o, i, s;
	if (!e.equals(t)) {
		var r = e.v;
		(at ? ht.set(e, t) : ht.set(e, r), (e.v = t));
		var n = _e.ensure();
		if ((n.capture(e, r), p)) {
			if (rt || h !== null) {
				(o = e.updated) != null || (e.updated = new Map());
				let a = ((s = (i = e.updated.get("")) == null ? void 0 : i.count) != null ? s : 0) + 1;
				if ((e.updated.set("", { error: null, count: a }), rt || a > 5)) {
					let f = dt("updated at");
					if (f !== null) {
						let c = e.updated.get(f.stack);
						(c || ((c = { error: f, count: 0 }), e.updated.set(f.stack, c)), c.count++);
					}
				}
			}
			h !== null && (e.set_during_effect = !0);
		}
		if ((e.f & 2) !== 0) {
			let a = e;
			((e.f & 2048) !== 0 && ln(a), Nr(a));
		}
		((e.wv = Pr()),
			ns(e, 2048),
			mt() && h !== null && (h.f & 1024) !== 0 && (h.f & 96) === 0 && (Pe === null ? os([e]) : Pe.push(e)),
			!n.is_fork && hr.size > 0 && !Vo && Fn());
	}
	return t;
}
function Fn() {
	Vo = !1;
	var e = Ot;
	Ir(!0);
	let t = Array.from(hr);
	try {
		for (let r of t) ((r.f & 1024) !== 0 && O(r, 4096), Zt(r) && Xt(r));
	} finally {
		Ir(e);
	}
	hr.clear();
}
function dr(e) {
	Z(e, e.v + 1);
}
function ns(e, t) {
	var m;
	var r = e.reactions;
	if (r !== null)
		for (var n = mt(), o = r.length, i = 0; i < o; i++) {
			var s = r[i],
				a = s.f;
			if (!(!n && s === h)) {
				if (p && (a & 131072) !== 0) {
					hr.add(s);
					continue;
				}
				var f = (a & 2048) === 0;
				if ((f && O(s, t), (a & 2) !== 0)) {
					var c = s;
					((m = z) == null || m.delete(c), (a & 32768) === 0 && (a & 512 && (s.f |= 32768), ns(c, 4096)));
				} else f && ((a & 16) !== 0 && $e !== null && $e.add(s), Oe(s));
			}
		}
}
var ma = /^[a-zA-Z_$][a-zA-Z_$0-9]*$/;
function er(e) {
	if (typeof e != "object" || e === null || oe in e) return e;
	let t = Er(e);
	if (t !== bo && t !== yi) return e;
	var r = new Map(),
		n = At(e),
		o = Ke(0),
		i = p && rt ? dt("created at") : null,
		s = tr,
		a = (_) => {
			if (tr === s) return _();
			var u = x,
				d = tr;
			(U(null), Yo(s));
			var v = _();
			return (U(u), Yo(d), v);
		};
	n && (r.set("length", Ke(e.length, i)), p && (e = ha(e)));
	var f = "";
	let c = !1;
	function m(_) {
		if (!c) {
			((c = !0), (f = _), Ee(o, `${f} version`));
			for (let [u, d] of r) Ee(d, xr(f, u));
			c = !1;
		}
	}
	return new Proxy(e, {
		defineProperty(_, u, d) {
			(!("value" in d) || d.configurable === !1 || d.enumerable === !1 || d.writable === !1) && Ri();
			var v = r.get(u);
			return (
				v === void 0
					? (v = a(() => {
							var g = Ke(d.value, i);
							return (r.set(u, g), p && typeof u == "string" && Ee(g, xr(f, u)), g);
						}))
					: Z(v, d.value, !0),
				!0
			);
		},
		deleteProperty(_, u) {
			var d = r.get(u);
			if (d === void 0) {
				if (u in _) {
					let v = a(() => Ke(I, i));
					(r.set(u, v), dr(o), p && Ee(v, xr(f, u)));
				}
			} else (Z(d, I), dr(o));
			return !0;
		},
		get(_, u, d) {
			var P;
			if (u === oe) return e;
			if (p && u === $n) return m;
			var v = r.get(u),
				g = u in _;
			if (
				(v === void 0 &&
					(!g || ((P = Ce(_, u)) != null && P.writable)) &&
					((v = a(() => {
						var xe = er(g ? _[u] : I),
							D = Ke(xe, i);
						return (p && Ee(D, xr(f, u)), D);
					})),
					r.set(u, v)),
				v !== void 0)
			) {
				var A = N(v);
				return A === I ? void 0 : A;
			}
			return Reflect.get(_, u, d);
		},
		getOwnPropertyDescriptor(_, u) {
			var d = Reflect.getOwnPropertyDescriptor(_, u);
			if (d && "value" in d) {
				var v = r.get(u);
				v && (d.value = N(v));
			} else if (d === void 0) {
				var g = r.get(u),
					A = g == null ? void 0 : g.v;
				if (g !== void 0 && A !== I) return { enumerable: !0, configurable: !0, value: A, writable: !0 };
			}
			return d;
		},
		has(_, u) {
			var A;
			if (u === oe) return !0;
			var d = r.get(u),
				v = (d !== void 0 && d.v !== I) || Reflect.has(_, u);
			if (d !== void 0 || (h !== null && (!v || ((A = Ce(_, u)) != null && A.writable)))) {
				d === void 0 &&
					((d = a(() => {
						var P = v ? er(_[u]) : I,
							xe = Ke(P, i);
						return (p && Ee(xe, xr(f, u)), xe);
					})),
					r.set(u, d));
				var g = N(d);
				if (g === I) return !1;
			}
			return v;
		},
		set(_, u, d, v) {
			var ye;
			var g = r.get(u),
				A = u in _;
			if (n && u === "length")
				for (var P = d; P < g.v; P += 1) {
					var xe = r.get(P + "");
					xe !== void 0
						? Z(xe, I)
						: P in _ && ((xe = a(() => Ke(I, i))), r.set(P + "", xe), p && Ee(xe, xr(f, P)));
				}
			if (g === void 0)
				(!A || ((ye = Ce(_, u)) != null && ye.writable)) &&
					((g = a(() => Ke(void 0, i))), p && Ee(g, xr(f, u)), Z(g, er(d)), r.set(u, g));
			else {
				A = g.v !== I;
				var D = a(() => er(d));
				Z(g, D);
			}
			var K = Reflect.getOwnPropertyDescriptor(_, u);
			if ((K != null && K.set && K.set.call(v, d), !A)) {
				if (n && typeof u == "string") {
					var re = r.get("length"),
						be = Number(u);
					Number.isInteger(be) && be >= re.v && Z(re, be + 1);
				}
				dr(o);
			}
			return !0;
		},
		ownKeys(_) {
			N(o);
			var u = Reflect.ownKeys(_).filter((g) => {
				var A = r.get(g);
				return A === void 0 || A.v !== I;
			});
			for (var [d, v] of r) v.v !== I && !(d in _) && u.push(d);
			return u;
		},
		setPrototypeOf() {
			Di();
		},
	});
}
function xr(e, t) {
	var r;
	return typeof t == "symbol"
		? `${e}[Symbol(${(r = t.description) != null ? r : ""})]`
		: ma.test(t)
			? `${e}.${t}`
			: /^\d+$/.test(t)
				? `${e}[${t}]`
				: `${e}['${t}']`;
}
function Gn(e) {
	try {
		if (e !== null && typeof e == "object" && oe in e) return e[oe];
	} catch (t) {}
	return e;
}
var va = new Set(["copyWithin", "fill", "pop", "push", "reverse", "shift", "sort", "splice", "unshift"]);
function ha(e) {
	return new Proxy(e, {
		get(t, r, n) {
			var o = Reflect.get(t, r, n);
			return va.has(r)
				? function (...i) {
						rs();
						var s = o.apply(this, i);
						return (Fn(), s);
					}
				: o;
		},
	});
}
function is() {
	let e = Array.prototype,
		t = Array.__svelte_cleanup;
	t && t();
	let { indexOf: r, lastIndexOf: n, includes: o } = e;
	((e.indexOf = function (i, s) {
		let a = r.call(this, i, s);
		if (a === -1) {
			for (let f = s != null ? s : 0; f < this.length; f += 1)
				if (Gn(this[f]) === i) {
					Tn("array.indexOf(...)");
					break;
				}
		}
		return a;
	}),
		(e.lastIndexOf = function (i, s) {
			let a = n.call(this, i, s != null ? s : this.length - 1);
			if (a === -1) {
				for (let f = 0; f <= (s != null ? s : this.length - 1); f += 1)
					if (Gn(this[f]) === i) {
						Tn("array.lastIndexOf(...)");
						break;
					}
			}
			return a;
		}),
		(e.includes = function (i, s) {
			let a = o.call(this, i, s);
			if (!a) {
				for (let f = 0; f < this.length; f += 1)
					if (Gn(this[f]) === i) {
						Tn("array.includes(...)");
						break;
					}
			}
			return a;
		}),
		(Array.__svelte_cleanup = () => {
			((e.indexOf = r), (e.lastIndexOf = n), (e.includes = o));
		}));
}
var Uo, ss, Qr, as, fs;
function jn() {
	if (Uo === void 0) {
		((Uo = window), (ss = document), (Qr = /Firefox/.test(navigator.userAgent)));
		var e = Element.prototype,
			t = Node.prototype,
			r = Text.prototype;
		((as = Ce(t, "firstChild").get),
			(fs = Ce(t, "nextSibling").get),
			yo(e) &&
				((e.__click = void 0),
				(e.__className = void 0),
				(e.__attributes = null),
				(e.__style = void 0),
				(e.__e = void 0)),
			yo(r) && (r.__t = void 0),
			p && ((e.__svelte_meta = null), is()));
	}
}
function ae(e = "") {
	return document.createTextNode(e);
}
function ve(e) {
	return as.call(e);
}
function se(e) {
	return fs.call(e);
}
function T(e, t) {
	if (!b) return ve(e);
	var r = ve(E);
	if (r === null) r = E.appendChild(ae());
	else if (t && r.nodeType !== Kr) {
		var n = ae();
		return (r == null || r.before(n), B(n), n);
	}
	return (B(r), r);
}
function Xe(e, t = !1) {
	var o, i;
	if (!b) {
		var r = ve(e);
		return r instanceof Comment && r.data === "" ? se(r) : r;
	}
	if (t && ((o = E) == null ? void 0 : o.nodeType) !== Kr) {
		var n = ae();
		return ((i = E) == null || i.before(n), B(n), n);
	}
	return E;
}
function F(e, t = 1, r = !1) {
	let n = b ? E : e;
	for (var o; t--; ) ((o = n), (n = se(n)));
	if (!b) return n;
	if (r && (n == null ? void 0 : n.nodeType) !== Kr) {
		var i = ae();
		return (n === null ? o == null || o.after(i) : n.before(i), B(i), i);
	}
	return (B(n), n);
}
function zn(e) {
	e.textContent = "";
}
function Ho() {
	if (!we || $e !== null) return !1;
	var e = h.f;
	return (e & 32768) !== 0;
}
function rr(e) {
	var t = x,
		r = h;
	(U(null), W(null));
	try {
		return e();
	} finally {
		(U(t), W(r));
	}
}
function jo(e) {
	(h === null && (x === null && Ai(e), Ti()), at && Si(e));
}
function xa(e, t) {
	var r = t.last;
	r === null ? (t.last = t.first = e) : ((r.next = e), (e.prev = r), (t.last = e));
}
function ft(e, t, r) {
	var a;
	var n = h;
	if (p) for (; n !== null && (n.f & 131072) !== 0; ) n = n.parent;
	n !== null && (n.f & 8192) !== 0 && (e |= 8192);
	var o = {
		ctx: $,
		deps: null,
		nodes: null,
		f: e | 2048 | 512,
		first: null,
		fn: t,
		last: null,
		next: null,
		parent: n,
		b: n && n.b,
		prev: null,
		teardown: null,
		wv: 0,
		ac: null,
	};
	if ((p && (o.component_function = nt), r))
		try {
			(Xt(o), (o.f |= 32768));
		} catch (f) {
			throw (G(o), f);
		}
	else t !== null && Oe(o);
	var i = o;
	if (
		(r &&
			i.deps === null &&
			i.teardown === null &&
			i.nodes === null &&
			i.first === i.last &&
			(i.f & 524288) === 0 &&
			((i = i.first), (e & 16) !== 0 && (e & 65536) !== 0 && i !== null && (i.f |= 65536)),
		i !== null && ((i.parent = n), n !== null && xa(i, n), x !== null && (x.f & 2) !== 0 && (e & 64) === 0))
	) {
		var s = x;
		((a = s.effects) != null ? a : (s.effects = [])).push(i);
	}
	return o;
}
function Rt() {
	return x !== null && !Ae;
}
function te(e) {
	let t = ft(8, null, !1);
	return (O(t, 1024), (t.teardown = e), t);
}
function Ur(e) {
	var o;
	(jo("$effect"), p && X(e, "name", { value: "$effect" }));
	var t = h.f,
		r = !x && (t & 32) !== 0 && (t & 32768) === 0;
	if (r) {
		var n = $;
		((o = n.e) != null ? o : (n.e = [])).push(e);
	} else return $o(e);
}
function $o(e) {
	return ft(1048580, e, !1);
}
function cn(e) {
	return (jo("$effect.pre"), p && X(e, "name", { value: "$effect.pre" }), ft(1048584, e, !0));
}
function Wn(e) {
	_e.ensure();
	let t = ft(524352, e, !0);
	return () => {
		G(t);
	};
}
function cs(e) {
	_e.ensure();
	let t = ft(524352, e, !0);
	return (r = {}) =>
		new Promise((n) => {
			r.outro
				? Qt(t, () => {
						(G(t), n(void 0));
					})
				: (G(t), n(void 0));
		});
}
function Be(e) {
	return ft(4, e, !1);
}
function ts(e) {
	return ft(4718592, e, !0);
}
function ee(e, t = 0) {
	return ft(8 | t, e, !0);
}
function Ze(e, t = [], r = [], n = []) {
	Yn(n, t, r, (o) => {
		ft(8, () => e(...o.map(N)), !0);
	});
}
function We(e, t = 0) {
	var r = ft(16 | t, e, !0);
	return (p && (r.dev_stack = _t), r);
}
function me(e) {
	return ft(524320, e, !0);
}
function zo(e) {
	var t = e.teardown;
	if (t !== null) {
		let r = at,
			n = x;
		(Go(!0), U(null));
		try {
			t.call(null);
		} finally {
			(Go(r), U(n));
		}
	}
}
function Wo(e, t = !1) {
	var r = e.first;
	for (e.first = e.last = null; r !== null; ) {
		let o = r.ac;
		o !== null &&
			rr(() => {
				o.abort(pt);
			});
		var n = r.next;
		((r.f & 64) !== 0 ? (r.parent = null) : G(r, t), (r = n));
	}
}
function us(e) {
	for (var t = e.first; t !== null; ) {
		var r = t.next;
		((t.f & 32) === 0 && G(t), (t = r));
	}
}
function G(e, t = !0) {
	var r = !1;
	((t || (e.f & 262144) !== 0) &&
		e.nodes !== null &&
		e.nodes.end !== null &&
		(ps(e.nodes.start, e.nodes.end), (r = !0)),
		Wo(e, t && !r),
		un(e, 0),
		O(e, 16384));
	var n = e.nodes && e.nodes.t;
	if (n !== null) for (let i of n) i.stop();
	zo(e);
	var o = e.parent;
	(o !== null && o.first !== null && Co(e),
		p && (e.component_function = null),
		(e.next = e.prev = e.teardown = e.ctx = e.deps = e.fn = e.nodes = e.ac = null));
}
function ps(e, t) {
	for (; e !== null; ) {
		var r = e === t ? null : se(e);
		(e.remove(), (e = r));
	}
}
function Co(e) {
	var t = e.parent,
		r = e.prev,
		n = e.next;
	(r !== null && (r.next = n),
		n !== null && (n.prev = r),
		t !== null && (t.first === e && (t.first = n), t.last === e && (t.last = r)));
}
function Qt(e, t, r = !0) {
	var n = [];
	ds(e, n, !0);
	var o = () => {
			(r && G(e), t && t());
		},
		i = n.length;
	if (i > 0) {
		var s = () => --i || o();
		for (var a of n) a.out(s);
	} else o();
}
function ds(e, t, r) {
	if ((e.f & 8192) === 0) {
		e.f ^= 8192;
		var n = e.nodes && e.nodes.t;
		if (n !== null) for (let a of n) (a.is_global || r) && t.push(a);
		for (var o = e.first; o !== null; ) {
			var i = o.next,
				s = (o.f & 65536) !== 0 || ((o.f & 32) !== 0 && (e.f & 16) !== 0);
			(ds(o, t, s ? r : !1), (o = i));
		}
	}
}
function Ko(e) {
	_s(e, !0);
}
function _s(e, t) {
	if ((e.f & 8192) !== 0) {
		((e.f ^= 8192), (e.f & 1024) === 0 && (O(e, 2048), Oe(e)));
		for (var r = e.first; r !== null; ) {
			var n = r.next,
				o = (r.f & 65536) !== 0 || (r.f & 32) !== 0;
			(_s(r, o ? t : !1), (r = n));
		}
		var i = e.nodes && e.nodes.t;
		if (i !== null) for (let s of i) (s.is_global || t) && s.in();
	}
}
function Vn(e, t) {
	if (e.nodes)
		for (var r = e.nodes.start, n = e.nodes.end; r !== null; ) {
			var o = r === n ? null : se(r);
			(t.append(r), (r = o));
		}
}
var ms = null;
var Ot = !1;
function Ir(e) {
	Ot = e;
}
var at = !1;
function Go(e) {
	at = e;
}
var x = null,
	Ae = !1;
function U(e) {
	x = e;
}
var h = null;
function W(e) {
	h = e;
}
var ke = null;
function qo(e) {
	x !== null && (!we || (x.f & 2) !== 0) && (ke === null ? (ke = [e]) : ke.push(e));
}
var he = null,
	qe = 0,
	Pe = null;
function os(e) {
	Pe = e;
}
var vs = 1,
	pn = 0,
	tr = pn;
function Yo(e) {
	tr = e;
}
function Pr() {
	return ++vs;
}
function Zt(e) {
	var t = e.f;
	if ((t & 2048) !== 0) return !0;
	if ((t & 2 && (e.f &= -32769), (t & 4096) !== 0)) {
		for (var r = e.deps, n = r.length, o = 0; o < n; o++) {
			var i = r[o];
			if ((Zt(i) && Bo(i), i.wv > e.wv)) return !0;
		}
		(t & 512) !== 0 && z === null && O(e, 1024);
	}
	return !1;
}
function hs(e, t, r = !0) {
	var n = e.reactions;
	if (n !== null && !(!we && ke != null && ke.includes(e)))
		for (var o = 0; o < n.length; o++) {
			var i = n[o];
			(i.f & 2) !== 0 ? hs(i, t, !1) : t === i && (r ? O(i, 2048) : (i.f & 1024) !== 0 && O(i, 4096), Oe(i));
		}
}
function Hn(e) {
	var v, g;
	var t = he,
		r = qe,
		n = Pe,
		o = x,
		i = ke,
		s = $,
		a = Ae,
		f = tr,
		c = e.f;
	((he = null),
		(qe = 0),
		(Pe = null),
		(x = (c & 96) === 0 ? e : null),
		(ke = null),
		Dt(e.ctx),
		(Ae = !1),
		(tr = ++pn),
		e.ac !== null &&
			(rr(() => {
				e.ac.abort(pt);
			}),
			(e.ac = null)));
	try {
		e.f |= 2097152;
		var m = e.fn,
			_ = m(),
			u = e.deps;
		if (he !== null) {
			var d;
			if ((un(e, qe), u !== null && qe > 0))
				for (u.length = qe + he.length, d = 0; d < he.length; d++) u[qe + d] = he[d];
			else e.deps = u = he;
			if (Rt() && (e.f & 512) !== 0)
				for (d = qe; d < u.length; d++) ((g = (v = u[d]).reactions) != null ? g : (v.reactions = [])).push(e);
		} else u !== null && qe < u.length && (un(e, qe), (u.length = qe));
		if (mt() && Pe !== null && !Ae && u !== null && (e.f & 6146) === 0)
			for (d = 0; d < Pe.length; d++) hs(Pe[d], e);
		return (
			o !== null && o !== e && (pn++, Pe !== null && (n === null ? (n = Pe) : n.push(...Pe))),
			(e.f & 8388608) !== 0 && (e.f ^= 8388608),
			_
		);
	} catch (A) {
		return Rn(A);
	} finally {
		((e.f ^= 2097152), (he = t), (qe = r), (Pe = n), (x = o), (ke = i), Dt(s), (Ae = a), (tr = f));
	}
}
function ba(e, t) {
	let r = t.reactions;
	if (r !== null) {
		var n = bi.call(r, e);
		if (n !== -1) {
			var o = r.length - 1;
			o === 0 ? (r = t.reactions = null) : ((r[n] = r[o]), r.pop());
		}
	}
	if (r === null && (t.f & 2) !== 0 && (he === null || !he.includes(t))) {
		var i = t;
		((i.f & 512) !== 0 && ((i.f ^= 512), (i.f &= -32769)), Nr(i), Un(i), un(i, 0));
	}
}
function un(e, t) {
	var r = e.deps;
	if (r !== null) for (var n = t; n < r.length; n++) ba(e, r[n]);
}
function Xt(e) {
	var f;
	var t = e.f;
	if ((t & 16384) === 0) {
		O(e, 1024);
		var r = h,
			n = Ot;
		if (((h = e), (Ot = !0), p)) {
			var o = nt;
			Cn(e.component_function);
			var i = _t;
			Ar((f = e.dev_stack) != null ? f : _t);
		}
		try {
			((t & 16777232) !== 0 ? us(e) : Wo(e), zo(e));
			var s = Hn(e);
			if (
				((e.teardown = typeof s == "function" ? s : null),
				(e.wv = vs),
				p && rt && (e.f & 2048) !== 0 && e.deps !== null)
			)
				for (var a of e.deps) a.set_during_effect && ((a.wv = Pr()), (a.set_during_effect = !1));
		} finally {
			((Ot = n), (h = r), p && (Cn(o), Ar(i)));
		}
	}
}
function N(e) {
	var d, v, g;
	var t = e.f,
		r = (t & 2) !== 0;
	if (((d = ms) == null || d.add(e), x !== null && !Ae)) {
		var n = h !== null && (h.f & 16384) !== 0;
		if (!n && !(ke != null && ke.includes(e))) {
			var o = x.deps;
			if ((x.f & 2097152) !== 0)
				e.rv < pn &&
					((e.rv = pn),
					he === null && o !== null && o[qe] === e
						? qe++
						: he === null
							? (he = [e])
							: he.includes(e) || he.push(e));
			else {
				((v = x.deps) != null ? v : (x.deps = [])).push(e);
				var i = e.reactions;
				i === null ? (e.reactions = [x]) : i.includes(x) || i.push(x);
			}
		}
	}
	if (p && (fn.delete(e), rt && !Ae && Jr !== null && x !== null && Jr.reaction === x))
		if (e.trace) e.trace();
		else {
			var s = dt("traced at");
			if (s) {
				var a = Jr.entries.get(e);
				a === void 0 && ((a = { traces: [] }), Jr.entries.set(e, a));
				var f = a.traces[a.traces.length - 1];
				s.stack !== (f == null ? void 0 : f.stack) && a.traces.push(s);
			}
		}
	if (at && ht.has(e)) return ht.get(e);
	if (r) {
		var c = e;
		if (at) {
			var m = c.v;
			return ((((c.f & 1024) === 0 && c.reactions !== null) || xs(c)) && (m = ln(c)), ht.set(c, m), m);
		}
		var _ = (c.f & 512) === 0 && !Ae && x !== null && (Ot || (x.f & 512) !== 0),
			u = c.deps === null;
		(Zt(c) && (_ && (c.f |= 512), Bo(c)), _ && !u && gs(c));
	}
	if ((g = z) != null && g.has(e)) return z.get(e);
	if ((e.f & 8388608) !== 0) throw e.v;
	return e.v;
}
function gs(e) {
	var t;
	if (e.deps !== null) {
		e.f |= 512;
		for (let r of e.deps)
			(((t = r.reactions) != null ? t : (r.reactions = [])).push(e),
				(r.f & 2) !== 0 && (r.f & 512) === 0 && gs(r));
	}
}
function xs(e) {
	if (e.v === I) return !0;
	if (e.deps === null) return !1;
	for (let t of e.deps) if (ht.has(t) || ((t.f & 2) !== 0 && xs(t))) return !0;
	return !1;
}
function L(e) {
	var t = Ae;
	try {
		return ((Ae = !0), e());
	} finally {
		Ae = t;
	}
}
function dn(e) {
	if (!(typeof e != "object" || !e || e instanceof EventTarget)) {
		if (oe in e) Kn(e);
		else if (!Array.isArray(e))
			for (let t in e) {
				let r = e[t];
				typeof r == "object" && r && oe in r && Kn(r);
			}
	}
}
function Kn(e, t = new Set()) {
	if (typeof e == "object" && e !== null && !(e instanceof EventTarget) && !t.has(e)) {
		(t.add(e), e instanceof Date && e.getTime());
		for (let n in e)
			try {
				Kn(e[n], t);
			} catch (o) {}
		let r = Er(e);
		if (
			r !== Object.prototype &&
			r !== Array.prototype &&
			r !== Map.prototype &&
			r !== Set.prototype &&
			r !== Date.prototype
		) {
			let n = xo(r);
			for (let o in n) {
				let i = n[o].get;
				if (i)
					try {
						i.call(e);
					} catch (s) {}
			}
		}
	}
}
var wa = [
	"allowfullscreen",
	"async",
	"autofocus",
	"autoplay",
	"checked",
	"controls",
	"default",
	"disabled",
	"formnovalidate",
	"indeterminate",
	"inert",
	"ismap",
	"loop",
	"multiple",
	"muted",
	"nomodule",
	"novalidate",
	"open",
	"playsinline",
	"readonly",
	"required",
	"reversed",
	"seamless",
	"selected",
	"webkitdirectory",
	"defer",
	"disablepictureinpicture",
	"disableremoteplayback",
];
var Cp = [
	...wa,
	"formNoValidate",
	"isMap",
	"noModule",
	"playsInline",
	"readOnly",
	"value",
	"volume",
	"defaultValue",
	"defaultChecked",
	"srcObject",
	"noValidate",
	"allowFullscreen",
	"disablePictureInPicture",
	"disableRemotePlayback",
];
var Ea = ["touchstart", "touchmove"];
function bs(e) {
	return Ea.includes(e);
}
var $a = ["$state", "$state.raw", "$derived", "$derived.by"],
	Rp = [
		...$a,
		"$state.eager",
		"$state.snapshot",
		"$props",
		"$props.id",
		"$bindable",
		"$effect",
		"$effect.pre",
		"$effect.tracking",
		"$effect.root",
		"$effect.pending",
		"$inspect",
		"$inspect().with",
		"$inspect.trace",
		"$host",
	];
var ws = new Map();
function Es(e, t) {
	var r = ws.get(e);
	(r || ((r = new Set()), ws.set(e, r)), r.add(t));
}
var Zo = new Set(),
	Xn = new Set();
function Ts(e, t, r, n = {}) {
	function o(i) {
		if ((n.capture || Gr.call(t, i), !i.cancelBubble)) return rr(() => (r == null ? void 0 : r.call(this, i)));
	}
	return (
		e.startsWith("pointer") || e.startsWith("touch") || e === "wheel"
			? pe(() => {
					t.addEventListener(e, o, n);
				})
			: t.addEventListener(e, o, n),
		o
	);
}
function Je(e, t, r, n, o) {
	var i = { capture: n, passive: o },
		s = Ts(e, t, r, i);
	(t === document.body || t === window || t === document || t instanceof HTMLMediaElement) &&
		te(() => {
			t.removeEventListener(e, s, i);
		});
}
function Hr(e) {
	for (var t = 0; t < e.length; t++) Zo.add(e[t]);
	for (var r of Xn) r(e);
}
var Ss = null;
function Gr(e) {
	var A;
	var t = this,
		r = t.ownerDocument,
		n = e.type,
		o = ((A = e.composedPath) == null ? void 0 : A.call(e)) || [],
		i = o[0] || e.target;
	Ss = e;
	var s = 0,
		a = Ss === e && e.__root;
	if (a) {
		var f = o.indexOf(a);
		if (f !== -1 && (t === document || t === window)) {
			e.__root = t;
			return;
		}
		var c = o.indexOf(t);
		if (c === -1) return;
		f <= c && (s = f);
	}
	if (((i = o[s] || e.target), i !== t)) {
		X(e, "currentTarget", {
			configurable: !0,
			get() {
				return i || r;
			},
		});
		var m = x,
			_ = h;
		(U(null), W(null));
		try {
			for (var u, d = []; i !== null; ) {
				var v = i.assignedSlot || i.parentNode || i.host || null;
				try {
					var g = i["__" + n];
					g != null && (!i.disabled || e.target === i) && g.call(i, e);
				} catch (P) {
					u ? d.push(P) : (u = P);
				}
				if (e.cancelBubble || v === t || v === null) break;
				i = v;
			}
			if (u) {
				for (let P of d)
					queueMicrotask(() => {
						throw P;
					});
				throw u;
			}
		} finally {
			((e.__root = t), delete e.currentTarget, U(m), W(_));
		}
	}
}
function Zn(e) {
	var t = document.createElement("template");
	return ((t.innerHTML = e.replaceAll("<!>", "<!---->")), t.content);
}
function yt(e, t) {
	var r = h;
	r.nodes === null && (r.nodes = { start: e, end: t, a: null, t: null });
}
function R(e, t) {
	var r = (t & 1) !== 0,
		n = (t & 2) !== 0,
		o,
		i = !e.startsWith("<!>");
	return () => {
		if (b) return (yt(E, null), E);
		o === void 0 && ((o = Zn(i ? e : "<!>" + e)), r || (o = ve(o)));
		var s = n || Qr ? document.importNode(o, !0) : o.cloneNode(!0);
		if (r) {
			var a = ve(s),
				f = s.lastChild;
			yt(a, f);
		} else yt(s, s);
		return s;
	};
}
function Jo() {
	if (b) return (yt(E, null), E);
	var e = document.createDocumentFragment(),
		t = document.createComment(""),
		r = ae();
	return (e.append(t, r), yt(t, r), e);
}
function C(e, t) {
	if (b) {
		var r = h;
		(((r.f & 32768) === 0 || r.nodes.end === null) && (r.nodes.end = E), le());
		return;
	}
	e !== null && e.before(t);
}
var Qo = !0;
function Ne(e, t) {
	var n;
	var r = t == null ? "" : typeof t == "object" ? t + "" : t;
	r !== ((n = e.__t) != null ? n : (e.__t = e.nodeValue)) && ((e.__t = r), (e.nodeValue = r + ""));
}
function wt(e, t) {
	return ks(e, t);
}
function ti(e, t) {
	var s;
	(jn(), (t.intro = (s = t.intro) != null ? s : !1));
	let r = t.target,
		n = b,
		o = E;
	try {
		for (var i = ve(r); i && (i.nodeType !== Re || i.data !== Xr); ) i = se(i);
		if (!i) throw Nt;
		(fe(!0), B(i));
		let a = ks(e, { ...t, anchor: i });
		return (fe(!1), a);
	} catch (a) {
		if (
			a instanceof Error &&
			a.message
				.split(
					`
`,
				)
				.some((f) => f.startsWith("https://svelte.dev/e/"))
		)
			throw a;
		return (
			a !== Nt && console.warn("Failed to hydrate: ", a),
			t.recover === !1 && Ni(),
			jn(),
			zn(r),
			fe(!1),
			wt(e, t)
		);
	} finally {
		(fe(n), B(o));
	}
}
var jr = new Map();
function ks(e, { target: t, anchor: r, props: n = {}, events: o, context: i, intro: s = !0 }) {
	jn();
	var a = new Set(),
		f = (_) => {
			for (var u = 0; u < _.length; u++) {
				var d = _[u];
				if (!a.has(d)) {
					a.add(d);
					var v = bs(d);
					t.addEventListener(d, Gr, { passive: v });
					var g = jr.get(d);
					g === void 0 ? (document.addEventListener(d, Gr, { passive: v }), jr.set(d, 1)) : jr.set(d, g + 1);
				}
			}
		};
	(f(ho(Zo)), Xn.add(f));
	var c = void 0,
		m = cs(() => {
			var _ = r != null ? r : t.appendChild(ae());
			return (
				Io(_, { pending: () => {} }, (u) => {
					if (i) {
						ce({});
						var d = $;
						d.c = i;
					}
					if (
						(o && (n.$$events = o),
						b && yt(u, null),
						(Qo = s),
						(c = e(u, n) || {}),
						(Qo = !0),
						b && ((h.nodes.end = E), E === null || E.nodeType !== Re || E.data !== $r))
					)
						throw (ir(), Nt);
					i && ue();
				}),
				() => {
					var v;
					for (var u of a) {
						t.removeEventListener(u, Gr);
						var d = jr.get(u);
						--d === 0 ? (document.removeEventListener(u, Gr), jr.delete(u)) : jr.set(u, d);
					}
					(Xn.delete(f), _ !== r && ((v = _.parentNode) == null || v.removeChild(_)));
				}
			);
		});
	return (ei.set(c, m), c);
}
var ei = new WeakMap();
function qt(e, t) {
	let r = ei.get(e);
	return r ? (ei.delete(e), r(t)) : (p && (oe in e ? Pi() : Fi()), Promise.resolve());
}
var lt,
	Et,
	Ve,
	br,
	_n,
	mn,
	Jn,
	Vt = class {
		constructor(t, r = !0) {
			M(this, "anchor");
			w(this, lt, new Map());
			w(this, Et, new Map());
			w(this, Ve, new Map());
			w(this, br, new Set());
			w(this, _n, !0);
			w(this, mn, () => {
				var t = k;
				if (l(this, lt).has(t)) {
					var r = l(this, lt).get(t),
						n = l(this, Et).get(r);
					if (n) (Ko(n), l(this, br).delete(r));
					else {
						var o = l(this, Ve).get(r);
						o &&
							(l(this, Et).set(r, o.effect),
							l(this, Ve).delete(r),
							o.fragment.lastChild.remove(),
							this.anchor.before(o.fragment),
							(n = o.effect));
					}
					for (let [i, s] of l(this, lt)) {
						if ((l(this, lt).delete(i), i === t)) break;
						let a = l(this, Ve).get(s);
						a && (G(a.effect), l(this, Ve).delete(s));
					}
					for (let [i, s] of l(this, Et)) {
						if (i === r || l(this, br).has(i)) continue;
						let a = () => {
							if (Array.from(l(this, lt).values()).includes(i)) {
								var c = document.createDocumentFragment();
								(Vn(s, c), c.append(ae()), l(this, Ve).set(i, { effect: s, fragment: c }));
							} else G(s);
							(l(this, br).delete(i), l(this, Et).delete(i));
						};
						l(this, _n) || !n ? (l(this, br).add(i), Qt(s, a, !1)) : a();
					}
				}
			});
			w(this, Jn, (t) => {
				l(this, lt).delete(t);
				let r = Array.from(l(this, lt).values());
				for (let [n, o] of l(this, Ve)) r.includes(n) || (G(o.effect), l(this, Ve).delete(n));
			});
			((this.anchor = t), y(this, _n, r));
		}
		ensure(t, r) {
			var n = k,
				o = Ho();
			if (r && !l(this, Et).has(t) && !l(this, Ve).has(t))
				if (o) {
					var i = document.createDocumentFragment(),
						s = ae();
					(i.append(s), l(this, Ve).set(t, { effect: me(() => r(s)), fragment: i }));
				} else
					l(this, Et).set(
						t,
						me(() => r(this.anchor)),
					);
			if ((l(this, lt).set(n, t), o)) {
				for (let [a, f] of l(this, Et)) a === t ? n.skipped_effects.delete(f) : n.skipped_effects.add(f);
				for (let [a, f] of l(this, Ve))
					a === t ? n.skipped_effects.delete(f.effect) : n.skipped_effects.add(f.effect);
				(n.oncommit(l(this, mn)), n.ondiscard(l(this, Jn)));
			} else (b && (this.anchor = E), l(this, mn).call(this));
		}
	};
((lt = new WeakMap()),
	(Et = new WeakMap()),
	(Ve = new WeakMap()),
	(br = new WeakMap()),
	(_n = new WeakMap()),
	(mn = new WeakMap()),
	(Jn = new WeakMap()));
function Qe(e, t, r = !1) {
	b && le();
	var n = new Vt(e),
		o = r ? 65536 : 0;
	function i(s, a) {
		if (b) {
			let c = wo(e) === kt;
			if (s === c) {
				var f = ar();
				(B(f), (n.anchor = f), fe(!1), n.ensure(s, a), fe(!0));
				return;
			}
		}
		n.ensure(s, a);
	}
	We(() => {
		var s = !1;
		(t((a, f = !0) => {
			((s = !0), i(f, a));
		}),
			s || i(!1, null));
	}, o);
}
function Ye(e, t) {
	Be(() => {
		var o;
		var r = e.getRootNode(),
			n = r.host ? r : (o = r.head) != null ? o : r.ownerDocument.head;
		if (!n.querySelector("#" + t.hash)) {
			let i = document.createElement("style");
			((i.id = t.hash), (i.textContent = t.code), n.appendChild(i), p && Es(t.hash, i));
		}
	});
}
function Yt(e, t, r) {
	Be(() => {
		var n = L(() => t(e, r == null ? void 0 : r()) || {});
		if (r && n != null && n.update) {
			var o = !1,
				i = {};
			(ee(() => {
				var s = r();
				(dn(s), o && Zr(i, s) && ((i = s), n.update(s)));
			}),
				(o = !0));
		}
		if (n != null && n.destroy) return () => n.destroy();
	});
}
var Ns = [
	...` 	
\r\f\xA0\v\uFEFF`,
];
function Rs(e, t, r) {
	var n = e == null ? "" : "" + e;
	if ((t && (n = n ? n + " " + t : t), r)) {
		for (var o in r)
			if (r[o]) n = n ? n + " " + o : o;
			else if (n.length)
				for (var i = o.length, s = 0; (s = n.indexOf(o, s)) >= 0; ) {
					var a = s + i;
					(s === 0 || Ns.includes(n[s - 1])) && (a === n.length || Ns.includes(n[a]))
						? (n = (s === 0 ? "" : n.substring(0, s)) + n.substring(a + 1))
						: (s = a);
				}
	}
	return n === "" ? null : n;
}
function Cs(e, t = !1) {
	var r = t ? " !important;" : ";",
		n = "";
	for (var o in e) {
		var i = e[o];
		i != null && i !== "" && (n += " " + o + ": " + i + r);
	}
	return n;
}
function ri(e) {
	return e[0] !== "-" || e[1] !== "-" ? e.toLowerCase() : e;
}
function Ds(e, t) {
	if (t) {
		var r = "",
			n,
			o;
		if ((Array.isArray(t) ? ((n = t[0]), (o = t[1])) : (n = t), e)) {
			e = String(e)
				.replaceAll(/\s*\/\*.*?\*\/\s*/g, "")
				.trim();
			var i = !1,
				s = 0,
				a = !1,
				f = [];
			(n && f.push(...Object.keys(n).map(ri)), o && f.push(...Object.keys(o).map(ri)));
			var c = 0,
				m = -1;
			let g = e.length;
			for (var _ = 0; _ < g; _++) {
				var u = e[_];
				if (
					(a
						? u === "/" && e[_ - 1] === "*" && (a = !1)
						: i
							? i === u && (i = !1)
							: u === "/" && e[_ + 1] === "*"
								? (a = !0)
								: u === '"' || u === "'"
									? (i = u)
									: u === "("
										? s++
										: u === ")" && s--,
					!a && i === !1 && s === 0)
				) {
					if (u === ":" && m === -1) m = _;
					else if (u === ";" || _ === g - 1) {
						if (m !== -1) {
							var d = ri(e.substring(c, m).trim());
							if (!f.includes(d)) {
								u !== ";" && _++;
								var v = e.substring(c, _).trim();
								r += " " + v + ";";
							}
						}
						((c = _ + 1), (m = -1));
					}
				}
			}
		}
		return (n && (r += Cs(n)), o && (r += Cs(o, !0)), (r = r.trim()), r === "" ? null : r);
	}
	return e == null ? null : String(e);
}
function Qn(e, t, r, n, o, i) {
	var s = e.__className;
	if (b || s !== r || s === void 0) {
		var a = Rs(r, n, i);
		((!b || a !== e.getAttribute("class")) &&
			(a == null ? e.removeAttribute("class") : t ? (e.className = a) : e.setAttribute("class", a)),
			(e.__className = r));
	} else if (i && o !== i)
		for (var f in i) {
			var c = !!i[f];
			(o == null || c !== !!o[f]) && e.classList.toggle(f, c);
		}
	return i;
}
function ni(e, t = {}, r, n) {
	for (var o in r) {
		var i = r[o];
		t[o] !== i && (r[o] == null ? e.style.removeProperty(o) : e.style.setProperty(o, i, n));
	}
}
function eo(e, t, r, n) {
	var o = e.__style;
	if (b || o !== t) {
		var i = Ds(t, n);
		((!b || i !== e.getAttribute("style")) && (i == null ? e.removeAttribute("style") : (e.style.cssText = i)),
			(e.__style = t));
	} else
		n &&
			(Array.isArray(n)
				? (ni(e, r == null ? void 0 : r[0], n[0]), ni(e, r == null ? void 0 : r[1], n[1], "important"))
				: ni(e, r, n));
	return n;
}
var Ya = Symbol("class"),
	Ua = Symbol("style"),
	Oh = Symbol("is custom element"),
	Ih = Symbol("is html");
function Ut(e = !1) {
	let t = $,
		r = t.l.u;
	if (!r) return;
	let n = () => dn(t.s);
	if (e) {
		let o = 0,
			i = {},
			s = Yr(() => {
				let a = !1,
					f = t.s;
				for (let c in f) f[c] !== i[c] && ((i[c] = f[c]), (a = !0));
				return (a && o++, o);
			});
		n = () => N(s);
	}
	(r.b.length &&
		cn(() => {
			(Os(t, n), or(r.b));
		}),
		Ur(() => {
			let o = L(() => r.m.map(wi));
			return () => {
				for (let i of o) typeof i == "function" && i();
			};
		}),
		r.a.length &&
			Ur(() => {
				(Os(t, n), or(r.a));
			}));
}
function Os(e, t) {
	if (e.l.s) for (let r of e.l.s) N(r);
	t();
}
function vn(e, t, r) {
	if (e == null) return (t(void 0), r && r(void 0), ne);
	let n = L(() => e.subscribe(t, r));
	return n.unsubscribe ? () => n.unsubscribe() : n;
}
var zr = [];
function ro(e, t) {
	return { subscribe: hn(e, t).subscribe };
}
function hn(e, t = ne) {
	let r = null,
		n = new Set();
	function o(a) {
		if (Zr(e, a) && ((e = a), r)) {
			let f = !zr.length;
			for (let c of n) (c[1](), zr.push(c, e));
			if (f) {
				for (let c = 0; c < zr.length; c += 2) zr[c][0](zr[c + 1]);
				zr.length = 0;
			}
		}
	}
	function i(a) {
		o(a(e));
	}
	function s(a, f = ne) {
		let c = [a, f];
		return (
			n.add(c),
			n.size === 1 && (r = t(o, i) || ne),
			a(e),
			() => {
				(n.delete(c), n.size === 0 && r && (r(), (r = null)));
			}
		);
	}
	return { set: o, update: i, subscribe: s };
}
function oi(e, t, r) {
	let n = !Array.isArray(e),
		o = n ? [e] : e;
	if (!o.every(Boolean)) throw new Error("derived() expects stores as input, got a falsy value");
	let i = t.length < 2;
	return ro(r, (s, a) => {
		let f = !1,
			c = [],
			m = 0,
			_ = ne,
			u = () => {
				if (m) return;
				_();
				let v = t(n ? c[0] : c, s, a);
				i ? s(v) : (_ = typeof v == "function" ? v : ne);
			},
			d = o.map((v, g) =>
				vn(
					v,
					(A) => {
						((c[g] = A), (m &= ~(1 << g)), f && u());
					},
					() => {
						m |= 1 << g;
					},
				),
			);
		return (
			(f = !0),
			u(),
			function () {
				(or(d), _(), (f = !1));
			}
		);
	});
}
function no(e) {
	let t;
	return (vn(e, (r) => (t = r))(), t);
}
var ii = Symbol();
function ge(e, t, r) {
	var i;
	let n = (i = r[t]) != null ? i : (r[t] = { store: null, source: gr(void 0), unsubscribe: ne });
	if ((p && (n.source.label = t), n.store !== e && !(ii in r)))
		if ((n.unsubscribe(), (n.store = e != null ? e : null), e == null))
			((n.source.v = void 0), (n.unsubscribe = ne));
		else {
			var o = !0;
			((n.unsubscribe = vn(e, (s) => {
				o ? (n.source.v = s) : Z(n.source, s);
			})),
				(o = !1));
		}
	return e && ii in r ? no(e) : N(n.source);
}
function ct() {
	let e = {};
	function t() {
		te(() => {
			for (var r in e) e[r].unsubscribe();
			X(e, ii, { enumerable: !1, value: !0 });
		});
	}
	return [e, t];
}
function Is(e) {
	return new si(e);
}
var Ht,
	et,
	si = class {
		constructor(t) {
			w(this, Ht);
			w(this, et);
			var i, s;
			var r = new Map(),
				n = (a, f) => {
					var c = gr(f, !1, !1);
					return (r.set(a, c), c);
				};
			let o = new Proxy(
				{ ...(t.props || {}), $$events: {} },
				{
					get(a, f) {
						var c;
						return N((c = r.get(f)) != null ? c : n(f, Reflect.get(a, f)));
					},
					has(a, f) {
						var c;
						return f === En
							? !0
							: (N((c = r.get(f)) != null ? c : n(f, Reflect.get(a, f))), Reflect.has(a, f));
					},
					set(a, f, c) {
						var m;
						return (Z((m = r.get(f)) != null ? m : n(f, c), c), Reflect.set(a, f, c));
					},
				},
			);
			(y(
				this,
				et,
				(t.hydrate ? ti : wt)(t.component, {
					target: t.target,
					anchor: t.anchor,
					props: o,
					context: t.context,
					intro: (i = t.intro) != null ? i : !1,
					recover: t.recover,
				}),
			),
				!we && (!((s = t == null ? void 0 : t.props) != null && s.$$host) || t.sync === !1) && Fr(),
				y(this, Ht, o.$$events));
			for (let a of Object.keys(l(this, et)))
				a === "$set" ||
					a === "$destroy" ||
					a === "$on" ||
					X(this, a, {
						get() {
							return l(this, et)[a];
						},
						set(f) {
							l(this, et)[a] = f;
						},
						enumerable: !0,
					});
			((l(this, et).$set = (a) => {
				Object.assign(o, a);
			}),
				(l(this, et).$destroy = () => {
					qt(l(this, et));
				}));
		}
		$set(t) {
			l(this, et).$set(t);
		}
		$on(t, r) {
			l(this, Ht)[t] = l(this, Ht)[t] || [];
			let n = (...o) => r.call(this, ...o);
			return (
				l(this, Ht)[t].push(n),
				() => {
					l(this, Ht)[t] = l(this, Ht)[t].filter((o) => o !== n);
				}
			);
		}
		$destroy() {
			l(this, et).$destroy();
		}
	};
((Ht = new WeakMap()), (et = new WeakMap()));
var Ja;
typeof HTMLElement == "function" &&
	(Ja = class extends HTMLElement {
		constructor(t, r, n) {
			super();
			M(this, "$$ctor");
			M(this, "$$s");
			M(this, "$$c");
			M(this, "$$cn", !1);
			M(this, "$$d", {});
			M(this, "$$r", !1);
			M(this, "$$p_d", {});
			M(this, "$$l", {});
			M(this, "$$l_u", new Map());
			M(this, "$$me");
			((this.$$ctor = t), (this.$$s = r), n && this.attachShadow({ mode: "open" }));
		}
		addEventListener(t, r, n) {
			if (((this.$$l[t] = this.$$l[t] || []), this.$$l[t].push(r), this.$$c)) {
				let o = this.$$c.$on(t, r);
				this.$$l_u.set(r, o);
			}
			super.addEventListener(t, r, n);
		}
		removeEventListener(t, r, n) {
			if ((super.removeEventListener(t, r, n), this.$$c)) {
				let o = this.$$l_u.get(r);
				o && (o(), this.$$l_u.delete(r));
			}
		}
		async connectedCallback() {
			if (((this.$$cn = !0), !this.$$c)) {
				let t = function (o) {
					return (i) => {
						let s = document.createElement("slot");
						(o !== "default" && (s.name = o), C(i, s));
					};
				};
				if ((await Promise.resolve(), !this.$$cn || this.$$c)) return;
				let r = {},
					n = Qa(this);
				for (let o of this.$$s)
					o in n &&
						(o === "default" && !this.$$d.children
							? ((this.$$d.children = t(o)), (r.default = !0))
							: (r[o] = t(o)));
				for (let o of this.attributes) {
					let i = this.$$g_p(o.name);
					i in this.$$d || (this.$$d[i] = ai(i, o.value, this.$$p_d, "toProp"));
				}
				for (let o in this.$$p_d)
					!(o in this.$$d) && this[o] !== void 0 && ((this.$$d[o] = this[o]), delete this[o]);
				((this.$$c = Is({
					component: this.$$ctor,
					target: this.shadowRoot || this,
					props: { ...this.$$d, $$slots: r, $$host: this },
				})),
					(this.$$me = Wn(() => {
						ee(() => {
							var o;
							this.$$r = !0;
							for (let i of go(this.$$c)) {
								if (!((o = this.$$p_d[i]) != null && o.reflect)) continue;
								this.$$d[i] = this.$$c[i];
								let s = ai(i, this.$$d[i], this.$$p_d, "toAttribute");
								s == null
									? this.removeAttribute(this.$$p_d[i].attribute || i)
									: this.setAttribute(this.$$p_d[i].attribute || i, s);
							}
							this.$$r = !1;
						});
					})));
				for (let o in this.$$l)
					for (let i of this.$$l[o]) {
						let s = this.$$c.$on(o, i);
						this.$$l_u.set(i, s);
					}
				this.$$l = {};
			}
		}
		attributeChangedCallback(t, r, n) {
			var o;
			this.$$r ||
				((t = this.$$g_p(t)),
				(this.$$d[t] = ai(t, n, this.$$p_d, "toProp")),
				(o = this.$$c) == null || o.$set({ [t]: this.$$d[t] }));
		}
		disconnectedCallback() {
			((this.$$cn = !1),
				Promise.resolve().then(() => {
					!this.$$cn && this.$$c && (this.$$c.$destroy(), this.$$me(), (this.$$c = void 0));
				}));
		}
		$$g_p(t) {
			return (
				go(this.$$p_d).find(
					(r) => this.$$p_d[r].attribute === t || (!this.$$p_d[r].attribute && r.toLowerCase() === t),
				) || t
			);
		}
	});
function ai(e, t, r, n) {
	var i;
	let o = (i = r[e]) == null ? void 0 : i.type;
	if (((t = o === "Boolean" && typeof t != "boolean" ? t != null : t), !n || !r[e])) return t;
	if (n === "toAttribute")
		switch (o) {
			case "Object":
			case "Array":
				return t == null ? null : JSON.stringify(t);
			case "Boolean":
				return t ? "" : null;
			case "Number":
				return t == null ? null : t;
			default:
				return t;
		}
	else
		switch (o) {
			case "Object":
			case "Array":
				return t && JSON.parse(t);
			case "Boolean":
				return t;
			case "Number":
				return t != null ? +t : t;
			default:
				return t;
		}
}
function Qa(e) {
	let t = {};
	return (
		e.childNodes.forEach((r) => {
			t[r.slot || "default"] = !0;
		}),
		t
	);
}
if (p) {
	let e = function (t) {
		if (!(t in globalThis)) {
			let r;
			Object.defineProperty(globalThis, t, {
				configurable: !0,
				get: () => {
					if (r !== void 0) return r;
					Ci(t);
				},
				set: (n) => {
					r = n;
				},
			});
		}
	};
	(e("$state"), e("$effect"), e("$derived"), e("$inspect"), e("$props"), e("$bindable"));
}
function Ls(e) {
	($ === null && Sn("onMount"),
		Ct && $.l !== null
			? ef($).m.push(e)
			: Ur(() => {
					let t = L(e);
					if (typeof t == "function") return t;
				}));
}
function ef(e) {
	var r;
	var t = e.l;
	return (r = t.u) != null ? r : (t.u = { a: [], b: [], m: [] });
}
var Fs = "5";
var Ps, Bs, qs;
typeof window != "undefined" &&
	((qs = (Bs = (Ps = window.__svelte) != null ? Ps : (window.__svelte = {})).v) != null
		? qs
		: (Bs.v = new Set())
	).add(Fs);
qi();
var Gt = hn(),
	jt = ro(null, (e) => {
		let t,
			r = Gt.subscribe((n) => {
				n &&
					((t = n.sessionManager),
					e(t.getActiveSession()),
					t.onChange(() => {
						e(t.getActiveSession());
					}));
			});
		return () => {
			r();
		};
	}),
	oo = oi(
		jt,
		(e, t) => {
			if (!e || e.status === "completed") {
				t(0);
				return;
			}
			let r = () => {
				if (e.status === "running") {
					let o = nr(e.durationMinutes, e.elapsed, e.status, e.lastResumed);
					t(o);
				} else if (e.status === "paused") {
					let o = nr(e.durationMinutes, e.elapsed, e.status, e.lastResumed);
					t(o);
				}
			};
			r();
			let n = setInterval(r, 1e3);
			return () => {
				clearInterval(n);
			};
		},
		0,
	);
var tf = R('<h3 class="svelte-1mauid4"> </h3> <span> </span>', 1),
	rf = R('<h3 class="svelte-1mauid4">No active session</h3>'),
	nf = R('<div class="session-header svelte-1mauid4"><!></div>'),
	of = {
		hash: "svelte-1mauid4",
		code: ".session-header.svelte-1mauid4 {display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;padding-bottom:1rem;border-bottom:1px solid var(--background-modifier-border);}h3.svelte-1mauid4 {margin:0;}.status-tag.svelte-1mauid4 {padding:4px 8px;border-radius:4px;font-size:0.8em;text-transform:uppercase;font-weight:bold;}.status-tag.running.svelte-1mauid4 {background-color:var(--interactive-accent);color:var(--text-on-accent);}.status-tag.paused.svelte-1mauid4 {background-color:var(--background-modifier-warning);color:var(--text-normal);}.status-tag.completed.svelte-1mauid4 {background-color:var(--background-modifier-success);color:var(--text-on-accent);}",
	};
function fi(e, t) {
	(ce(t, !1), Ye(e, of));
	let r = () => ge(jt, "$session", n),
		[n, o] = ct();
	Ut();
	var i = nf(),
		s = T(i);
	{
		var a = (c) => {
				var m = tf(),
					_ = Xe(m),
					u = T(_, !0);
				S(_);
				var d = F(_, 2),
					v = T(d, !0);
				(S(d),
					Ze(() => {
						var g;
						(Ne(u, r().name),
							Qn(d, 1, `status-tag ${(g = r().status) != null ? g : ""}`, "svelte-1mauid4"),
							Ne(v, r().status));
					}),
					C(c, m));
			},
			f = (c) => {
				var m = rf();
				C(c, m);
			};
		Qe(s, (c) => {
			r() ? c(a) : c(f, !1);
		});
	}
	(S(i), C(e, i), ue(), o());
}
var sf = R(
		'<div class="time-display svelte-1a9y1bm"> </div> <div class="progress-bar-container svelte-1a9y1bm"><div class="progress-bar svelte-1a9y1bm"></div></div>',
		1,
	),
	af = R('<div class="time-display placeholder svelte-1a9y1bm">--:--</div>'),
	ff = R('<div class="session-timer svelte-1a9y1bm"><!></div>'),
	lf = {
		hash: "svelte-1a9y1bm",
		code: ".session-timer.svelte-1a9y1bm {text-align:center;margin:2rem 0;}.time-display.svelte-1a9y1bm {font-size:3em;font-family:var(--font-monospace);font-weight:bold;color:var(--text-normal);}.time-display.placeholder.svelte-1a9y1bm {opacity:0.5;}.progress-bar-container.svelte-1a9y1bm {height:4px;background-color:var(--background-modifier-border);border-radius:2px;margin-top:1rem;overflow:hidden;}.progress-bar.svelte-1a9y1bm {height:100%;background-color:var(--interactive-accent);transition:width 1s linear;}",
	};
function li(e, t) {
	(ce(t, !1), Ye(e, lf));
	let r = () => ge(jt, "$session", o),
		n = () => ge(oo, "$timeRemaining", o),
		[o, i] = ct();
	Ut();
	var s = ff(),
		a = T(s);
	{
		var f = (m) => {
				var _ = sf(),
					u = Xe(_),
					d = T(u, !0);
				S(u);
				var v = F(u, 2),
					g = T(v);
				(S(v),
					Ze(
						(A) => {
							(Ne(d, A), eo(g, `width: ${(r().elapsed / (r().durationMinutes * 60)) * 100}%`));
						},
						[() => wr(n())],
					),
					C(m, _));
			},
			c = (m) => {
				var _ = af();
				C(m, _);
			};
		Qe(a, (m) => {
			r() ? m(f) : m(c, !1);
		});
	}
	(S(s), C(e, s), ue(), i());
}
var ci = require("obsidian"),
	cf = R(
		'<div class="fs-status-msg svelte-xg6qn1">Session Completed</div> <button class="fs-control-btn fs-primary svelte-xg6qn1" aria-label="Finish"><div></div></button>',
		1,
	),
	uf = R('<button class="fs-control-btn fs-primary svelte-xg6qn1" aria-label="Pause"><div></div></button>'),
	pf = R('<button class="fs-control-btn fs-primary svelte-xg6qn1" aria-label="Resume"><div></div></button>'),
	df = R(
		'<button class="fs-control-btn fs-secondary svelte-xg6qn1" aria-label="Stop Session"><div></div></button> <!>',
		1,
	),
	_f = R(
		'<button class="fs-control-btn fs-secondary svelte-xg6qn1" aria-label="Short Break"><div></div></button> <button class="fs-control-btn fs-primary svelte-xg6qn1" aria-label="Start Focus"><div></div></button> <button class="fs-control-btn fs-secondary svelte-xg6qn1" aria-label="Long Break"><div></div></button>',
		1,
	),
	mf = R(
		'<div class="fs-controls-row fs-mt-2 svelte-xg6qn1"><button class="fs-control-text-btn svelte-xg6qn1">+30s</button> <button class="fs-control-text-btn svelte-xg6qn1">+1m</button> <button class="fs-control-text-btn svelte-xg6qn1">+5m</button></div>',
	),
	vf = R('<div class="fs-controls svelte-xg6qn1"><div class="fs-controls-row svelte-xg6qn1"><!></div> <!></div>'),
	hf = {
		hash: "svelte-xg6qn1",
		code: ".fs-controls.svelte-xg6qn1 {display:flex;flex-direction:column;align-items:center;gap:1rem;}.fs-controls-row.svelte-xg6qn1 {display:flex;gap:1rem;align-items:center;justify-content:center;}.fs-mt-2.svelte-xg6qn1 {margin-top:0.5rem;}.fs-control-btn.svelte-xg6qn1 {display:flex;align-items:center;justify-content:center;width:40px;height:40px;border-radius:50%;border:none;cursor:pointer;background-color:var(--interactive-normal);color:var(--text-normal);transition:background-color 0.2s;padding:0;}.fs-control-btn.svelte-xg6qn1:hover {background-color:var(--interactive-hover);}.fs-control-btn.fs-primary.svelte-xg6qn1 {background-color:var(--interactive-accent);color:var(--text-on-accent);}.fs-control-btn.fs-primary.svelte-xg6qn1:hover {background-color:var(--interactive-accent-hover);}.fs-control-text-btn.svelte-xg6qn1 {background:none;border:1px solid var(--background-modifier-border);padding:4px 8px;border-radius:4px;cursor:pointer;font-size:0.8em;color:var(--text-muted);}.fs-control-text-btn.svelte-xg6qn1:hover {background-color:var(--background-modifier-hover);color:var(--text-normal);}.fs-status-msg.svelte-xg6qn1 {font-weight:bold;color:var(--text-success);margin-right:1rem;}",
	};
function ui(e, t) {
	(ce(t, !1), Ye(e, hf));
	let r = () => ge(Gt, "$plugin", o),
		n = () => ge(jt, "$session", o),
		[o, i] = ct();
	function s(D, K) {
		return (
			(0, ci.setIcon)(D, K),
			{
				update(re) {
					(D.empty(), (0, ci.setIcon)(D, re));
				},
			}
		);
	}
	function a(D) {
		r() === null || r() === void 0 || r().sessionManager.startSession(D);
	}
	function f() {
		r() === null || r() === void 0 || r().sessionManager.stopSession();
	}
	function c() {
		r() === null || r() === void 0 || r().sessionManager.pauseSession();
	}
	function m() {
		r() === null || r() === void 0 || r().sessionManager.resumeSession();
	}
	function _(D) {
		r() === null || r() === void 0 || r().sessionManager.addTime(D);
	}
	Ut();
	var u = vf(),
		d = T(u),
		v = T(d);
	{
		var g = (D) => {
				var K = Jo(),
					re = Xe(K);
				{
					var be = (zt) => {
							var $t = cf(),
								ut = F(Xe($t), 2),
								St = T(ut);
							(Yt(
								St,
								(Tt, uo) => (s == null ? void 0 : s(Tt, uo)),
								() => "check",
							),
								S(ut),
								Je("click", ut, f),
								C(zt, $t));
						},
						ye = (zt) => {
							var $t = df(),
								ut = Xe($t),
								St = T(ut);
							(Yt(
								St,
								(Wt, tt) => (s == null ? void 0 : s(Wt, tt)),
								() => "square",
							),
								S(ut));
							var Tt = F(ut, 2);
							{
								var uo = (Wt) => {
										var tt = uf(),
											po = T(tt);
										(Yt(
											po,
											(_o, mo) => (s == null ? void 0 : s(_o, mo)),
											() => "pause",
										),
											S(tt),
											Je("click", tt, c),
											C(Wt, tt));
									},
									Ws = (Wt) => {
										var tt = pf(),
											po = T(tt);
										(Yt(
											po,
											(_o, mo) => (s == null ? void 0 : s(_o, mo)),
											() => "play",
										),
											S(tt),
											Je("click", tt, m),
											C(Wt, tt));
									};
								Qe(Tt, (Wt) => {
									n().status === "running" ? Wt(uo) : Wt(Ws, !1);
								});
							}
							(Je("click", ut, f), C(zt, $t));
						};
					Qe(re, (zt) => {
						n().status === "completed" ? zt(be) : zt(ye, !1);
					});
				}
				C(D, K);
			},
			A = (D) => {
				var K = _f(),
					re = Xe(K),
					be = T(re);
				(Yt(
					be,
					(St, Tt) => (s == null ? void 0 : s(St, Tt)),
					() => "coffee",
				),
					S(re));
				var ye = F(re, 2),
					zt = T(ye);
				(Yt(
					zt,
					(St, Tt) => (s == null ? void 0 : s(St, Tt)),
					() => "play",
				),
					S(ye));
				var $t = F(ye, 2),
					ut = T($t);
				(Yt(
					ut,
					(St, Tt) => (s == null ? void 0 : s(St, Tt)),
					() => "armchair",
				),
					S($t),
					Je("click", re, () => a("Short Break")),
					Je("click", ye, () => a("Deep Work")),
					Je("click", $t, () => a("Long Break")),
					C(D, K));
			};
		Qe(v, (D) => {
			n() ? D(g) : D(A, !1);
		});
	}
	S(d);
	var P = F(d, 2);
	{
		var xe = (D) => {
			var K = mf(),
				re = T(K),
				be = F(re, 2),
				ye = F(be, 2);
			(S(K), Je("click", re, () => _(0.5)), Je("click", be, () => _(1)), Je("click", ye, () => _(5)), C(D, K));
		};
		Qe(P, (D) => {
			n() && (n().status === "running" || n().status === "paused") && D(xe);
		});
	}
	(S(u), C(e, u), ue(), i());
}
var gf = R('<div class="session-footer svelte-vabpp2"><small> </small></div>'),
	xf = {
		hash: "svelte-vabpp2",
		code: ".session-footer.svelte-vabpp2 {margin-top:auto;padding-top:1rem;text-align:center;color:var(--text-faint);border-top:1px solid var(--background-modifier-border);}",
	};
function pi(e, t) {
	(ce(t, !1), Ye(e, xf));
	let r = () => ge(Gt, "$plugin", n),
		[n, o] = ct();
	Ut();
	var i = gf(),
		s = T(i),
		a = T(s);
	(S(s),
		S(i),
		Ze(() => {
			var f, c;
			return Ne(a, `v${(c = (f = r()) == null ? void 0 : f.manifest.version) != null ? c : ""}`);
		}),
		C(e, i),
		ue(),
		o());
}
var bf = R('<div class="focus-session-container svelte-76swht"><!> <!> <!> <!></div>'),
	yf = {
		hash: "svelte-76swht",
		code: ".focus-session-container.svelte-76swht {display:flex;flex-direction:column;height:100%;padding:1rem;}",
	};
function di(e) {
	Ye(e, yf);
	var t = bf(),
		r = T(t);
	fi(r, {});
	var n = F(r, 2);
	li(n, {});
	var o = F(n, 2);
	ui(o, {});
	var i = F(o, 2);
	(pi(i, {}), S(t), C(e, t));
}
var gn = "focus-session-view",
	io = class extends Vs.ItemView {
		constructor(r, n, o) {
			super(r);
			this.component = null;
			((this.sessionManager = n), (this.pluginVersion = o));
		}
		getViewType() {
			return gn;
		}
		getDisplayText() {
			return "Focus sessions";
		}
		async onOpen() {
			let r = this.contentEl;
			(r.empty(), r.addClass("focus-session-view"), (this.component = wt(di, { target: r })));
		}
		async onClose() {
			this.component && qt(this.component);
		}
	};
var Ys = require("obsidian");
var wf = R(
		'<h2> </h2> <div class="stats svelte-1fktv0t"><p> </p> <p> </p></div> <button class="mod-warning svelte-1fktv0t">Stop session</button>',
		1,
	),
	Ef = R("<h2>No active session</h2> <p>Go to the side panel to start a new session.</p>", 1),
	$f = R('<div class="session-modal-content svelte-1fktv0t"><!></div>'),
	Sf = {
		hash: "svelte-1fktv0t",
		code: ".session-modal-content.svelte-1fktv0t {text-align:center;padding:1rem;}.stats.svelte-1fktv0t {margin:1.5rem 0;font-size:1.1em;}button.svelte-1fktv0t {cursor:pointer;}",
	};
function _i(e, t) {
	(ce(t, !0), Ye(e, Sf));
	let r = () => ge(Gt, "$plugin", i),
		n = () => ge(jt, "$session", i),
		o = () => ge(oo, "$timeRemaining", i),
		[i, s] = ct();
	function a() {
		(r() === null || r() === void 0 || r().sessionManager.stopSession(), t.close());
	}
	var f = $f(),
		c = T(f);
	{
		var m = (u) => {
				var d = wf(),
					v = Xe(d),
					g = T(v, !0);
				S(v);
				var A = F(v, 2),
					P = T(A),
					xe = T(P);
				S(P);
				var D = F(P, 2),
					K = T(D);
				(S(D), S(A));
				var re = F(A, 2);
				((re.__click = a),
					Ze(
						(be) => {
							var ye;
							(Ne(g, n().name),
								Ne(xe, `Duration: ${(ye = n().durationMinutes) != null ? ye : ""} minutes`),
								Ne(K, `Time remaining: ${be != null ? be : ""}`));
						},
						[() => wr(o())],
					),
					C(u, d));
			},
			_ = (u) => {
				var d = Ef();
				(sr(2), C(u, d));
			};
		Qe(c, (u) => {
			n() ? u(m) : u(_, !1);
		});
	}
	(S(f), C(e, f), ue(), s());
}
Hr(["click"]);
var so = class extends Ys.Modal {
	constructor(r) {
		super(r);
		this.component = null;
	}
	onOpen() {
		this.component = wt(_i, { target: this.contentEl, props: { close: () => this.close() } });
	}
	onClose() {
		(this.component && qt(this.component), this.contentEl.empty());
	}
};
var Us = require("obsidian");
var ao = class extends Us.Modal {
	constructor(t, r) {
		(super(t), (this.sessionManager = r));
	}
	onOpen() {
		let { contentEl: t } = this;
		(t.addClass("fs-session-end-modal"), t.createEl("h2", { text: "Focus session completed!" }));
		let r = t.createDiv({ cls: "fs-modal-controls" }),
			n = r.createDiv({ cls: "fs-extension-options" });
		n.createDiv({ cls: "fs-label", text: "Need more time?" });
		let o = n.createDiv({ cls: "fs-controls-row" });
		([
			{ label: "+30s", val: 0.5 },
			{ label: "+1m", val: 1 },
			{ label: "+5m", val: 5 },
		].forEach((a) => {
			let f = o.createEl("button", { cls: "fs-control-text-btn", text: a.label });
			f.onclick = () => {
				(this.sessionManager.addTime(a.val), this.close());
			};
		}),
			r.createDiv({ cls: "fs-spacer" }));
		let s = r.createEl("button", { cls: "mod-cta fs-finish-btn", text: "Finish session" });
		s.onclick = () => {
			(this.sessionManager.stopSession(), this.close());
		};
	}
	onClose() {
		let { contentEl: t } = this;
		t.empty();
		let r = this.sessionManager.getActiveSession();
		r && r.status === "completed" && this.sessionManager.stopSession();
	}
};
var Gs = require("obsidian");
var Hs = require("obsidian"),
	Tf =
		R(`<div class="svelte-modal-content"><h2></h2> <p>This is a reactive Svelte 5 component using Runes.</p> <div class="counter-section"><p>Count: <strong> </strong></p> <button>Increment</button></div> <style>.svelte-modal-content {
			padding: 1rem;
			text-align: center;
		}
		.counter-section {
			margin-top: 2rem;
			padding: 1rem;
			background-color: var(--background-secondary);
			border-radius: 8px;
		}
		button {
			margin-top: 1rem;
			cursor: pointer;
		}</style></div>`);
function mi(e, t) {
	ce(t, !0);
	let r = Ke(0),
		n = "Hello Svelte 5!";
	function o() {
		(Z(r, N(r) + 1), new Hs.Notice(`Count is now ${N(r)}`));
	}
	Ls(() => {
		console.log("Svelte 5 component mounted in app:", t.app);
	});
	var i = Tf(),
		s = T(i);
	s.textContent = "Hello Svelte 5!";
	var a = F(s, 4),
		f = T(a),
		c = F(T(f)),
		m = T(c, !0);
	(S(c), S(f));
	var _ = F(f, 2);
	((_.__click = o), S(a), sr(2), S(i), Ze(() => Ne(m, N(r))), C(e, i), ue());
}
Hr(["click"]);
var fo = class extends Gs.Modal {
	constructor(r) {
		super(r);
		this.component = null;
	}
	onOpen() {
		let { contentEl: r } = this;
		(r.empty(), (this.component = wt(mi, { target: r, props: { app: this.app } })));
	}
	onClose() {
		let { contentEl: r } = this;
		(this.component && qt(this.component), r.empty());
	}
};
var js = { focusDuration: 25, shortBreakDuration: 5, longBreakDuration: 15, enableSound: !0 };
var Wr = require("obsidian");
var lo = class extends Wr.PluginSettingTab {
	constructor(t, r) {
		(super(t, r), (this.plugin = r));
	}
	display() {
		let { containerEl: t } = this;
		(t.empty(),
			new Wr.Setting(t)
				.setName("Focus duration (minutes)")
				.setDesc("The length of a focus session.")
				.addSlider((r) =>
					r
						.setLimits(1, 120, 1)
						.setValue(this.plugin.settings.focusDuration)
						.setDynamicTooltip()
						.onChange(async (n) => {
							((this.plugin.settings.focusDuration = n), await this.plugin.saveSettings());
						}),
				),
			new Wr.Setting(t)
				.setName("Short break duration (minutes)")
				.setDesc("The length of a short break.")
				.addSlider((r) =>
					r
						.setLimits(1, 30, 1)
						.setValue(this.plugin.settings.shortBreakDuration)
						.setDynamicTooltip()
						.onChange(async (n) => {
							((this.plugin.settings.shortBreakDuration = n), await this.plugin.saveSettings());
						}),
				),
			new Wr.Setting(t)
				.setName("Long break duration (minutes)")
				.setDesc("The length of a long break.")
				.addSlider((r) =>
					r
						.setLimits(1, 60, 1)
						.setValue(this.plugin.settings.longBreakDuration)
						.setDynamicTooltip()
						.onChange(async (n) => {
							((this.plugin.settings.longBreakDuration = n), await this.plugin.saveSettings());
						}),
				));
	}
};
var co = class extends zs.Plugin {
	async onload() {
		(await this.loadSettings(),
			Gt.set(this),
			(this.audioService = new bn(this.settings.enableSound)),
			(this.sessionManager = new yn(this.settings, this.audioService)),
			this.registerView(gn, (t) => new io(t, this.sessionManager, this.manifest.version)),
			this.addRibbonIcon("clock", "Open focus sessions", () => {
				this.activateView();
			}),
			this.addCommand({
				id: "open-test-svelte-modal",
				name: "Open test svelte modal",
				callback: () => {
					new fo(this.app).open();
				},
			}),
			(this.statusBarItemEl = this.addStatusBarItem()),
			this.updateStatusBar(),
			this.sessionManager.onChange(() => {
				this.updateStatusBar();
			}),
			this.sessionManager.onSessionComplete(() => {
				new ao(this.app, this.sessionManager).open();
			}),
			this.registerInterval(
				window.setInterval(() => {
					(this.sessionManager.tick(), this.updateStatusBar());
				}, 1e3),
			),
			this.statusBarItemEl.addClass("mod-clickable"),
			this.statusBarItemEl.onClickEvent(() => {
				new so(this.app).open();
			}),
			this.addSettingTab(new lo(this.app, this)));
	}
	async loadSettings() {
		this.settings = Object.assign({}, js, await this.loadData());
	}
	async saveSettings() {
		await this.saveData(this.settings);
	}
	onunload() {}
	updateStatusBar() {
		let t = this.sessionManager.getActiveSession();
		if (t) {
			let r = nr(t.durationMinutes, t.elapsed, t.status, t.lastResumed),
				n = wr(r);
			this.statusBarItemEl.setText(`${t.name} (${n})`);
		} else this.statusBarItemEl.setText("");
	}
	async activateView() {
		let { workspace: t } = this.app,
			r = null,
			n = t.getLeavesOfType(gn);
		if (n.length > 0) r = n[0];
		else {
			let o = t.getRightLeaf(!1);
			o && ((r = o), await r.setViewState({ type: gn, active: !0 }));
		}
		r && t.revealLeaf(r);
	}
};
